#!/usr/bin/env python3
"""The kb's roots (stdlib only): list them, or add one beside kb/public.

  kbroot.py list                         name, id prefix, visibility, articles, sources and path of every root
  kbroot.py add NAME --prefix P [--visibility internal|public] [--description TEXT]
                                         create kb/NAME/: its _root.md, empty ledgers with their headers, a coverage
                                         page with the table markers and _retrieval/ with empty data tables

A root is a directory of knowledge with its own sources and id prefix (kbcommon.py, "Roots"): kb/public holds the
upstream facts, and a team adds its own roots (its systems, its repositories, its internal runbooks) beside it.
NAME: lowercase letters, digits and `-`. P: 1-4 capital letters, not taken by another root and not one of
kbcommon.RESERVED_PREFIXES. `internal` (the default) exempts the root from the placeholders-only rule; `public`
keeps it (AGENTS.md, "Agent conduct").

Exit: 0 done, 2 refused (bad name or prefix, taken, or the directory exists).
"""
import argparse, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_index, kbcommon  # noqa: E402

SOURCES_HEADER = "id,url,title,publisher,licence,reuse,retrieved_utc,version_or_date,artifact_sha256,used_in,superseded_by\n"
FILES = {
    kbcommon.SOURCES: SOURCES_HEADER,
    kbcommon.ARTIFACTS: "path,source_id,sha256,zip_member\n",
    kbcommon.STATE: "id,url,checked_utc,fetched_utc,changed_utc,sha256,text_sha256,bytes,error\n",
    kbcommon.COVERAGE_CSV: ",".join(build_index.COVERAGE_FIELDS) + "\n",
    kbcommon.ANSWERS: "# Answers to research questions\n\nEach answer is headed `## QK-<slug>. <question>` "
                      "(`python3 _tools/kbid.py answer \"<question>\" --root {name}`); every bullet carries one tag.\n",
    kbcommon.GAPS: "# Gaps (UNK items: what was tried, where)\n",
    kbcommon.CONFLICTS: "# Conflicts (both sources linked)\n",
    kbcommon.DATA_DIR + "/lookup_eval.csv": "id,question,expect_paths,expect_verdict,allow_weak\n",
    kbcommon.DATA_DIR + "/signals.csv": "signal,topic\n",
    kbcommon.DATA_DIR + "/index_extra.csv": "topic,priority,status,files\n",
}


def root_md(name, prefix, visibility, description):
    return (f"---\nroot: {name}\nid_prefix: {prefix}\nvisibility: {visibility}\ndescription: {description}\n---\n\n"
            f"# {name}\n\n{description or 'A knowledge root.'}\n\nSource ids of this root are `{prefix}-<8 characters>`: "
            f"`python3 _tools/kbid.py url <URL> --root {name}`.\n")


def cmd_list():
    try:
        roots = kbcommon.roots()
    except kbcommon.RootError as e:
        print("ERROR", e)
        return 2
    for r in roots:
        n_art = sum(1 for p in build_index.content_files(r)
                    if p.endswith(".md") and build_index.front_matter(build_index.read(p, r) or "") is not None)
        try:
            n_src = len(kbcommon.load_csv(os.path.join(r.path, kbcommon.SOURCES), ("id",))[1])
        except kbcommon.CsvError:
            n_src = 0
        where = os.path.relpath(r.path, kbcommon.HOME) if r.path.startswith(kbcommon.HOME + os.sep) else r.path
        print(f"{r.name}\tprefix={r.id_prefix}\t{r.visibility}\tarticles={n_art}\tsources={n_src}\t{where}")
    print(f"roots={len(roots)}")
    return 0


def cmd_add(a):
    name, prefix = a.name, a.prefix
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name) or name == "kb":
        print(f"refused: root name {name!r} must be lowercase letters, digits and -")
        return 2
    if not kbcommon.PREFIX.fullmatch(prefix) or prefix in kbcommon.RESERVED_PREFIXES:
        print(f"refused: id prefix {prefix!r} must be 1-4 capital letters, not one of "
              f"{', '.join(sorted(kbcommon.RESERVED_PREFIXES))}")
        return 2
    try:
        roots = kbcommon.roots()
    except kbcommon.RootError as e:
        print("refused: fix the existing roots first:", e)
        return 2
    for r in roots:
        if r.name == name or r.id_prefix == prefix:
            print(f"refused: root {r.name} ({r.path}) already has the {'name' if r.name == name else 'id prefix'} "
                  f"{name if r.name == name else prefix!r}")
            return 2
    d = os.path.join(kbcommon.KB_DIR, name)
    if os.path.exists(d):
        print(f"refused: {os.path.relpath(d, kbcommon.HOME)} exists")
        return 2
    os.makedirs(os.path.join(d, kbcommon.DATA_DIR))
    files = {kbcommon.ROOT_FILE: root_md(name, prefix, a.visibility, " ".join(a.description.split())),
             kbcommon.COVERAGE_MD: f"# Coverage: {name}\n\nEvery topic of this root, generated by "
                                   f"`python3 _tools/build_index.py`: never edit the table by hand.\n\n"
                                   f"{build_index.START}\n{build_index.END}\n",
             **{k: v.format(name=name) for k, v in FILES.items()}}
    for rel, text in files.items():
        with open(os.path.join(d, rel), "w", encoding="utf-8", newline="") as f:
            f.write(text)
    print(f"created {os.path.relpath(d, kbcommon.HOME)}/ (root {name}, id prefix {prefix}, {a.visibility}): "
          f"add domain directories of articles, then python3 _tools/build_index.py and python3 _tools/check.py")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list", help="every root")
    ad = sub.add_parser("add", help="create a root beside kb/public")
    ad.add_argument("name")
    ad.add_argument("--prefix", required=True, help="the root's source id prefix: 1-4 capital letters")
    ad.add_argument("--visibility", choices=("internal", "public"), default="internal")
    ad.add_argument("--description", default="", help="one line: what the root holds")
    a = ap.parse_args()
    return cmd_list() if a.cmd == "list" else cmd_add(a)


if __name__ == "__main__":
    sys.exit(main())
