"""kbingest.py reads a team's repository that is not trusted: its survey leaves out secrets, generated and vendored
files; its map never runs the repository's code, never follows a link out of it, hands every child a scrubbed
environment and redacts leaks from what it writes. One planted failure each."""
import json, os, shutil, subprocess, sys
from pathlib import Path

import pytest

from conftest import TOOLS, Repo, git_env, requires_git

import kbingest

pytestmark = [pytest.mark.git, requires_git]

TOOL = str(Path(TOOLS) / "kbingest.py")
GIT_DIR = os.path.dirname(os.path.abspath(shutil.which("git") or "git"))  # kbingest runs git from PATH


def run(*args, cwd=None, env=None):
    p = subprocess.run([sys.executable, TOOL, *args], capture_output=True, text=True, encoding="utf-8",
                       errors="replace", env=env or git_env(), cwd=cwd, timeout=120)
    return p.returncode, p.stdout + p.stderr


def commit_files(path, files, executable=()):
    r = Repo(path)
    Path(r.path).mkdir(parents=True)
    r.git("init", "-q", "-b", "main")
    for rel, text in files.items():
        r.write(rel, text)
    r.git("add", "-A")
    for rel in executable:
        r.git("update-index", "--chmod=+x", rel)
    r.git("commit", "-q", "-m", "init")
    return r


def map_doc(repo, out, *args, **kw):
    code, text = run("map", repo.path, "--out", str(out), *args, **kw)
    assert code == 0, text
    return json.loads(Path(out).read_text(encoding="utf-8")), text


def test_survey_leaves_out_and_keeps(tmp_path):
    secret = "pass" + "word: '" + "x" * 12 + "'\n"  # built here so the leak scan of this file stays clean
    gen = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"
    r = commit_files(tmp_path / "deploy", {
        "README.md": "# deploy\n", "src/app.py": "print('hi')\n", "config/app.yaml": "name: deploy\n" + secret,
        ".env": "TOKEN=x\n", ".env.example": "TOKEN=\n", "certs/server.key": "k\n", "vendor/lib.js": "x\n",
        "third_party/kept.py": "x = 1\n", "third_party/other.py": "x = 2\n", "package-lock.json": "{}\n",
        "api/gen.go": gen, "api/keep.go": gen,
        ".gitattributes": "third_party/kept.py -linguist-vendored\napi/keep.go -linguist-generated\n"})
    code, out = run("survey", r.path, "--files")
    assert code == 0, out
    rows = {tuple(ln.split("\t")[:3]) for ln in out.splitlines() if ln.startswith(("keep\t", "skip\t"))}
    for path, reason in {(".env", "secret-file"), ("certs/server.key", "secret-file"), ("vendor/lib.js", "vendored"),
                         ("third_party/other.py", "vendored"), ("package-lock.json", "generated"),
                         ("api/gen.go", "generated")}:
        assert ("skip", reason, path) in rows, (path, out)
    for path, kind in {("README.md", "doc"), ("src/app.py", "code"), ("config/app.yaml", "config"),
                       (".env.example", "config"), ("third_party/kept.py", "code"), ("api/keep.go", "code")}:
        assert ("keep", kind, path) in rows, (path, out)
    flagged = [ln.split("\t")[2] for ln in out.splitlines() if ln.startswith("keep\t") and ln.endswith("\tsecret")]
    assert flagged == ["config/app.yaml"], out  # a secret shape in a kept file is flagged, never printed
    assert "x" * 12 not in out


def test_map_never_runs_a_planted_ast_module(tmp_path):
    marker = tmp_path / "shadow-ran"
    r = commit_files(tmp_path / "shadow", {"ast.py": f"open({str(marker)!r}, 'w').close()\nimport sys\n",
                                           "m.py": "import os\n"})
    doc, _ = map_doc(r, tmp_path / "shadow.json", "--lang", "python")
    assert not marker.exists(), "the repository's ast.py ran"
    assert {i["path"]: i["imports"] for i in doc["imports"]} == {"ast.py": ["sys"], "m.py": ["os"]}  # parsed, not run


def test_map_never_runs_a_program_inside_the_worktree(tmp_path):
    marker = tmp_path / "program-ran"
    sh = f"#!/bin/sh\n: > '{marker}'\n"
    cmd = f'@echo off\r\ntype nul > "{marker}"\r\n'
    r = commit_files(tmp_path / "gorepo", {"go.mod": "module corp.example.com/app\n\ngo 1.21\n",
                                           "main.go": "package main\n\nfunc main() {}\n",
                                           "bin/go": sh, "bin/go.cmd": cmd, "go": sh, "go.cmd": cmd},
                     executable=("bin/go", "go"))
    # the repository's own `go` is reachable by a relative entry, an empty one, `.` (the current directory) and the
    # clone's absolute bin folder; git's own folder follows, as kbingest itself runs git
    path = os.pathsep.join(["bin", "", ".", str(Path(r.path) / "bin"), r.path, GIT_DIR])
    map_doc(r, tmp_path / "go.json", "--lang", "go", env=git_env(PATH=path), cwd=r.path)
    assert not marker.exists(), "the repository's own program ran"


def test_map_does_not_follow_a_symlink_out_of_the_repository(tmp_path):
    outside = tmp_path / "outside.py"
    outside.write_text("import stolen_module\n", encoding="utf-8")
    r = Repo(tmp_path / "links")
    Path(r.path).mkdir()
    r.git("init", "-q", "-b", "main")
    r.write("pkg/ok.py", "import os\n")
    try:
        os.symlink(outside, Path(r.path) / "pkg" / "link.py")
    except (OSError, NotImplementedError, AttributeError):
        pytest.skip("symbolic links are not available here")
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    if r.git("ls-files", "-s", "pkg/link.py").split()[0] != "120000":
        pytest.skip("git stores no symbolic link here")
    doc, text = map_doc(r, tmp_path / "links.json")
    assert "stolen_module" not in json.dumps(doc), text
    assert any(n["note"].startswith("pkg/link.py: not a regular file") for n in doc["notes"]), doc["notes"]


def test_map_child_environment_is_scrubbed(tmp_path, monkeypatch):
    """A mapper that runs a real child process: it prints the environment it got, and no planted secret is in it."""
    seen = {}
    secret = "s3" + "cr3t-" + "v" * 12
    code = "import json, os; print(json.dumps(dict(os.environ)))"

    class Probe(kbingest.Mapper):
        language, name, tool = "probe", "probe", sys.executable

        def files(self, rows):
            return [p for p, _k in rows if p.endswith(".py")]

        def map(self, ctx, files):
            seen.update(json.loads(ctx.run([self.tool, "-I", "-c", code], label="probe").out))

    r = commit_files(tmp_path / "envrepo", {"a.py": "x = 1\n"})
    outside = str(tmp_path / "tools")
    planted = {"GITLAB_" + "TOKEN": secret, "AWS_SECRET_" + "ACCESS_KEY": secret, "KB_TEST_UNLISTED": secret,
               "NODE_OPTIONS": "--require " + secret, "HTTPS_PROXY": "http://proxy.corp.example.com:8080"}
    for k, v in planted.items():
        monkeypatch.setenv(k, v)
    monkeypatch.setenv("PATH", os.pathsep.join(["bin", "", ".", str(Path(r.path) / "bin"), outside, GIT_DIR]))
    monkeypatch.setattr(kbingest, "MAPPERS", [Probe()])
    out = tmp_path / "env.json"
    assert kbingest.main(["map", r.path, "--out", str(out)]) == 0
    assert seen, "the probe child did not run"
    assert secret not in json.dumps(seen)
    assert not (set(planted) - {"HTTPS_PROXY"}) & set(seen)
    assert seen["HTTPS_PROXY"] == kbingest.NETWORK_OFF["HTTPS_PROXY"]  # the offline setting wins over the caller's
    assert seen["PATH"].split(os.pathsep) == [outside, GIT_DIR]  # no relative, empty or repository entry


def test_map_redacts_leaks_and_keeps_the_rest():
    token = "sk-" + "ant-" + "0" * 24
    doc = {"tools": {"x": {"version": "1.0 " + token}}, "packages": [{"name": "ok", "k": {token: "v", "a": "b"}}],
           "notes": [{"language": "x", "note": "fine"}]}
    out = kbingest.redact_leaks(doc)
    assert token not in json.dumps(out)
    assert out["tools"] == {"x": {"version": "<redacted>"}} and out["packages"] == [{"name": "ok", "k": {"a": "b"}}]
    notes = [n["note"] for n in out["notes"]]
    assert notes[0] == "fine" and len(notes) == 3 and all("redacted" in n for n in notes[1:])
