"""kbingest.py: the survey of a repository before /kb-ingest turns it into facts of a root.

A throwaway repository with planted files: secret files, vendored and generated code (by path, by .gitattributes,
by header), a binary and an oversized file are left out; an unset attribute keeps a file; a secret shape in a kept
file is flagged; an uncommitted change is not read; the pinned urls pass the CODE lint's pinned-source rule; remote
urls lose their credentials; the refusals exit 2.

The map command (`test_kbingest_map_*`): the scratch worktree is removed and holds the commit, not the working tree;
`python -m ast` in a subprocess maps a Python repository (imports, packages, entry points; a file named ast.py is never
run, vendored files are not mapped); a fake toolchain on PATH proves output parsing, the timeout, a missing tool, a bad
exit and output that is not JSON as notes, and that the environment is network-off and drops credentials; a map goes
under _cache/ingest/, never under kb/.
"""
import json, os, subprocess, sys, time
from pathlib import Path

import pytest

from conftest import Repo, TOOLS, git_env, requires_git

import kbfacts, kbingest

FAKE = Path(TOOLS) / "fixtures" / "kbingest" / "fakemap.py"

TOOL = str(Path(TOOLS) / "kbingest.py")
SECRET_LINE = "pass" + "word: '" + "x" * 12 + "'\n"  # built here so the leak scan of this file stays clean
GO_GEN = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"


def run(*args, cwd=None):
    p = subprocess.run([sys.executable, TOOL, *args], capture_output=True, text=True, encoding="utf-8",
                       errors="replace", env=git_env(), cwd=cwd, timeout=60)
    return p.returncode, p.stdout + p.stderr


@pytest.fixture(scope="module")
def repo(tmp_path_factory):
    r = Repo(tmp_path_factory.mktemp("ingest") / "deploy")
    Path(r.path).mkdir()
    r.git("init", "-q", "-b", "main")
    files = {
        "README.md": "# deploy\n", "src/app.py": "print('hi')\n", "tests/test_app.py": "def test(): pass\n",
        ".gitlab-ci.yml": "stages: [test]\n", "config/app.yaml": "name: deploy\n" + SECRET_LINE,
        ".env": "TOKEN=x\n", ".env.example": "TOKEN=\n", "certs/server.key": "k\n",
        "vendor/lib.js": "x\n", "third_party/kept.py": "x = 1\n", "third_party/other.py": "x = 2\n",
        "package-lock.json": "{}\n", "yarn.lock": "# lock\n", "api/client.py": "x = 3\n", "api/gen.go": GO_GEN,
        "api/keep.go": GO_GEN, "big.txt": "a" * 5000 + "\n",
        ".gitattributes": "api/client.py linguist-generated\nthird_party/kept.py -linguist-vendored\n"
                          "yarn.lock -gitlab-generated\napi/keep.go -linguist-generated\n",
    }
    for rel, text in files.items():
        r.write(rel, text)
    Path(r.file("assets/logo.png")).parent.mkdir(parents=True)
    Path(r.file("assets/logo.png")).write_bytes(b"\x89PNG\0\0\0binary")
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    r.git("remote", "add", "origin", "https://jan.kowalski:tok@gitlab.corp.example.com/ops/deploy.git")
    r.write("src/app.py", SECRET_LINE)  # uncommitted: the survey reads the commit, not the working tree
    return r


@requires_git
def test_survey_leaves_out_and_keeps(repo):
    code, out = run("survey", repo.path, "--files", "--max-bytes", "4000")
    assert code == 0, out
    lines = {tuple(ln.split("\t")[:3]) for ln in out.splitlines() if ln.startswith(("keep\t", "skip\t"))}
    want_skip = {(".env", "secret-file"), ("certs/server.key", "secret-file"), ("vendor/lib.js", "vendored"),
                 ("third_party/other.py", "vendored"), ("package-lock.json", "generated"), ("api/client.py", "generated"),
                 ("api/gen.go", "generated"), ("big.txt", "large"), ("assets/logo.png", "binary")}
    for path, reason in want_skip:
        assert ("skip", reason, path) in lines, (path, out)
    want_keep = {("README.md", "doc"), ("src/app.py", "code"), ("tests/test_app.py", "test"), (".gitlab-ci.yml", "ci"),
                 ("config/app.yaml", "config"), (".env.example", "config"), ("third_party/kept.py", "code"),
                 ("yarn.lock", "other"), ("api/keep.go", "code")}
    for path, kind in want_keep:
        assert ("keep", kind, path) in lines, (path, out)
    secret = [ln for ln in out.splitlines() if ln.startswith("keep\t") and ln.endswith("\tsecret")]
    assert [ln.split("\t")[2] for ln in secret] == ["config/app.yaml"], out  # src/app.py's change is uncommitted
    assert "tok" not in out and "jan.kowalski" not in out, "credentials in the remote url must never be printed"
    assert "remote: origin gitlab.corp.example.com/ops/deploy (forge gitlab)" in out
    assert "on a remote branch: no" in out and "worktree: differs from the commit" in out


@requires_git
def test_pinned_urls_pass_the_code_lint(repo):
    code, url = run("url", repo.path, "src/app.py")
    commit = repo.rev("HEAD")
    assert code == 0 and url.strip() == f"https://gitlab.corp.example.com/ops/deploy/-/raw/{commit}/src/app.py", url
    assert kbfacts.pinned_source({"url": url.strip()})
    assert run("url", repo.path, "no/such.py")[0] == 2


@requires_git
def test_refusals(repo, tmp_path):
    assert run("survey", str(tmp_path))[0] == 2  # not a repository
    assert run("survey", repo.path, "--rev", "no-such-rev")[0] == 2
    bare = Repo(tmp_path / "local")
    Path(bare.path).mkdir()
    bare.git("init", "-q")
    bare.write("a.py", "x = 1\n")
    bare.git("add", "-A")
    bare.git("commit", "-q", "-m", "a")
    code, out = run("url", bare.path, "a.py")
    assert code == 2 and "no pinned url form" in out  # no remote: nothing others could open
    code, out = run("survey", bare.path)
    assert code == 0 and "remote: none" in out


def test_parse_remote_and_forge():
    cases = {
        "git@gitlab.corp.example.com:ops/deploy.git": ("gitlab.corp.example.com", "ops/deploy"),
        "ssh://git@gitlab.corp.example.com:2222/ops/sub/deploy.git": ("gitlab.corp.example.com", "ops/sub/deploy"),
        "https://jan.kowalski:tok@gitlab.corp.example.com:8443/ops/deploy": ("gitlab.corp.example.com:8443", "ops/deploy"),
        "https://github.com/o/r.git": ("github.com", "o/r"),
        "/srv/git/deploy.git": (None, None), "../deploy": (None, None), "C:\\src\\deploy": (None, None),
    }
    for url, want in cases.items():
        assert kbingest.parse_remote(url) == want, url
    assert kbingest.forge_of("github.com") == "github" and kbingest.forge_of("gitlab.com") == "gitlab"
    assert kbingest.forge_of("git.corp.example.com") is None
    assert kbingest.forge_of("git.corp.example.com", "gitlab") == "gitlab"
    assert kbingest.pin_url("github", "github.com", "o/r", "ab" * 20, "a b.py") == \
        f"https://raw.githubusercontent.com/o/r/{'ab' * 20}/a%20b.py"
    assert kbingest.pin_url("github", "ghe.corp.example.com", "o/r", "ab" * 20, "a.py") is None


# ---- map ---------------------------------------------------------------------------------------------------------

def commit_files(path, files):
    r = Repo(path)
    Path(r.path).mkdir(parents=True)
    r.git("init", "-q", "-b", "main")
    for rel, text in files.items():
        r.write(rel, text)
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    return r


@pytest.fixture(scope="module")
def pyrepo(tmp_path_factory):
    r = commit_files(tmp_path_factory.mktemp("map") / "deploy", {
        "pkg/__init__.py": "",
        "pkg/core.py": "import os, sys\nfrom . import util\nfrom pkg.sub import thing as t\nimport a.b as ab\n"
                       "NOTE = 'Import(names=[alias(name=\"in_a_string\")])'\n\ndef main():\n    pass\n",
        "pkg/util.py": "from .. import up\nfrom .sibling import x\n",
        "pkg/sub/__init__.py": "", "pkg/sub/thing.py": "import json\n",
        "pkg/__main__.py": "from pkg import core\ncore.main()\n",
        "src/lib/__init__.py": "", "src/lib/x.py": "import re\n",
        "run.py": "import json\n\nif __name__ == '__main__':\n    print(json.dumps({}))\n",
        "tests/test_run.py": "import pytest\n",
        "broken.py": "def (:\n",
        "ast.py": "raise SystemExit(7)\n",  # `python -m ast` in the worktree root must not run this
        "vendor/lib.py": "import vendored_only\n",
        ".env": "TOKEN=x\n",
        "pyproject.toml": "[project]\nname = 'deploy'\n\n[project.scripts]\ndeploy = 'pkg.core:main'\n",
        "a.fake": "x\n", "b.fake": "y\n",
    })
    r.write("run.py", "import uncommitted_mod\n")  # not committed: the map reads the commit
    return r


def map_run(repo, out, *args, scratch=None):
    env = git_env()
    if scratch is not None:
        env.update(TMPDIR=str(scratch), TEMP=str(scratch), TMP=str(scratch))
    p = subprocess.run([sys.executable, TOOL, "map", repo.path, "--out", str(out), *args], capture_output=True,
                       text=True, encoding="utf-8", errors="replace", env=env, timeout=120)
    return p.returncode, p.stdout + p.stderr


def worktree_count(repo):
    return sum(1 for ln in repo.git("worktree", "list", "--porcelain").splitlines() if ln.startswith("worktree "))


@requires_git
def test_kbingest_map_python_ast_subprocess(pyrepo, tmp_path):
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    out = tmp_path / "deploy.json"
    code, text = map_run(pyrepo, out, "--lang", "python", scratch=scratch)
    assert code == 0, text
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert doc["format"] == 1 and doc["commit"] == pyrepo.rev("HEAD") and doc["repo"] == "deploy"
    assert doc["tools"]["python"]["tool"] == "python" and doc["tools"]["python"]["version"].startswith("Python 3.")
    assert "fake" not in doc["tools"]  # --lang python
    assert {(p["name"], p["path"]) for p in doc["packages"]} == \
        {("pkg", "pkg"), ("pkg.sub", "pkg/sub"), ("lib", "src/lib")}
    imports = {i["path"]: i["imports"] for i in doc["imports"]}
    assert imports["pkg/core.py"] == [".util", "a.b", "os", "pkg.sub", "sys"]  # the string that looks like a node is not one
    assert imports["pkg/util.py"] == ["..up", ".sibling"]
    assert imports["run.py"] == ["json"]  # the commit, not the working tree
    assert "vendored_only" not in json.dumps(doc) and not any(k.startswith("vendor/") for k in imports)
    kinds = {(e["path"], e["kind"]) for e in doc["entry_points"]}
    assert {("run.py", "main-guard"), ("pkg/__main__.py", "module-main")} <= kinds
    assert ("pyproject.toml", "console-script") in kinds
    notes = [n["note"] for n in doc["notes"]]
    assert any(n.startswith("python -m ast broken.py: exit 1") for n in notes), notes  # a syntax error is a note
    assert not any("exit 7" in n for n in notes), "the repository's ast.py ran"
    assert worktree_count(pyrepo) == 1 and list(scratch.iterdir()) == []  # the scratch worktree and its directory are gone
    assert pyrepo.path not in json.dumps(doc) and str(scratch) not in json.dumps(doc)


@requires_git
def test_kbingest_map_planted_ast_shadow_is_not_run(tmp_path):
    """Planted: a repository whose ast.py would print a marker if `-m ast` ran it from the working directory."""
    r = commit_files(tmp_path / "shadow", {"ast.py": "import sys\nsys.stderr.write('SHADOW RAN\\n')\nsys.exit(7)\n",
                                           "m.py": "import os\n"})
    out = tmp_path / "shadow.json"
    code, text = map_run(r, out, "--lang", "python")
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert code == 0 and "SHADOW RAN" not in text + json.dumps(doc), text
    assert {i["path"]: i["imports"] for i in doc["imports"]} == {"ast.py": ["sys"], "m.py": ["os"]}  # parsed, not run


@requires_git
def test_kbingest_map_symlink_is_not_followed(tmp_path):
    outside = tmp_path / "outside.py"
    outside.write_text("import stolen_module\n", encoding="utf-8")
    r = Repo(tmp_path / "links")
    Path(r.path).mkdir()
    r.git("init", "-q", "-b", "main")
    r.write("ok.py", "import os\n")
    try:
        os.symlink(outside, Path(r.path) / "link.py")
    except (OSError, NotImplementedError, AttributeError):
        pytest.skip("symbolic links are not available here")
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    if r.git("ls-files", "-s", "link.py").split()[0] != "120000":
        pytest.skip("git stores no symbolic link here")
    out = tmp_path / "links.json"
    code, text = map_run(r, out)
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert code == 0 and "stolen_module" not in json.dumps(doc), text
    assert any(n["note"].startswith("link.py: not a regular file") for n in doc["notes"]), doc["notes"]


# The fake toolchain: `fakemap` on PATH is a shim over fixtures/kbingest/fakemap.py.

def install_fake(tmp_path, monkeypatch, name="fakemap"):
    bindir = tmp_path / "bin"
    bindir.mkdir(exist_ok=True)
    if os.name == "nt":
        (bindir / f"{name}.cmd").write_text(f'@"{sys.executable}" "{FAKE}" %*\r\n', encoding="utf-8", newline="")
    else:
        shim = bindir / name
        shim.write_text(f'#!/bin/sh\nexec "{sys.executable}" "{FAKE}" "$@"\n', encoding="utf-8", newline="\n")
        shim.chmod(0o755)
    monkeypatch.setenv("PATH", str(bindir) + os.pathsep + os.environ.get("PATH", ""))
    return bindir


class FakeMapper(kbingest.Mapper):
    language = "fake"
    name = "fakemap"
    tool = "fakemap"

    def __init__(self, *steps, tool="fakemap"):
        self.steps, self.tool, self.seen = steps or ("list",), tool, {}

    def files(self, rows):
        return sorted(p for p, _k in rows if p.endswith(".fake"))

    def map(self, ctx, files):
        for step in self.steps:
            data = ctx.json([self.tool, step], label=f"fakemap {step}")
            self.seen[step] = data
            if isinstance(data, dict):
                for pkg in data.get("packages", []):
                    ctx.add_package(pkg["name"], pkg["path"])
                for path, mods in data.get("imports", {}).items():
                    ctx.add_imports(path, mods)
                for ep in data.get("entry_points", []):
                    ctx.add_entry_point(ep["path"], ep["kind"], ep.get("name"))


def fake_map(pyrepo, tmp_path, monkeypatch, mapper, *args):
    monkeypatch.setattr(kbingest, "MAPPERS", [mapper])
    out = tmp_path / "fake.json"
    code = kbingest.main(["map", pyrepo.path, "--out", str(out), *args])
    return code, json.loads(out.read_text(encoding="utf-8"))


@requires_git
def test_kbingest_map_fake_toolchain_output_is_parsed(pyrepo, tmp_path, monkeypatch):
    install_fake(tmp_path, monkeypatch)
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("list"))
    assert code == 0
    assert doc["tools"] == {"fake": {"tool": "fakemap", "version": "fakemap 1.2.3 (fake toolchain)"}}
    assert doc["packages"] == [{"language": "fake", "name": "app", "path": "src"}]
    assert doc["imports"] == [{"language": "fake", "path": "src/a.fake", "imports": ["x", "y"]}]  # sorted, de-duplicated
    assert doc["entry_points"] == [{"language": "fake", "path": "src/a.fake", "kind": "main", "name": "app"}]
    assert doc["notes"] == []  # an unknown field in the tool's output is ignored, not a note


@requires_git
def test_kbingest_map_fake_toolchain_timeout_is_a_note(pyrepo, tmp_path, monkeypatch):
    """Planted: a tool that sleeps 60 s under --timeout 2."""
    install_fake(tmp_path, monkeypatch)
    started = time.monotonic()
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("sleep", "list"), "--timeout", "2")
    assert time.monotonic() - started < 40
    assert code == 0
    assert {"language": "fake", "note": "fakemap sleep: timed out after 2s"} in doc["notes"], doc["notes"]
    assert doc["packages"] and doc["imports"], "the next command still ran after the timeout"
    assert worktree_count(pyrepo) == 1


@requires_git
def test_kbingest_map_missing_toolchain_is_a_note(pyrepo, tmp_path, monkeypatch):
    """Planted: a mapper whose program is on no PATH."""
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("list", tool="no-such-toolchain-kb"))
    assert code == 0, "a missing toolchain is a note, not an error"
    assert doc["tools"] == {} and doc["packages"] == [] and doc["imports"] == []
    assert doc["notes"] == [{"language": "fake",
                             "note": "toolchain not installed: fakemap (2 fake files not mapped)"}]


@requires_git
def test_kbingest_map_bad_output_and_exit_are_notes(pyrepo, tmp_path, monkeypatch):
    """Planted: output that is not JSON, and a non-zero exit with a stderr message."""
    install_fake(tmp_path, monkeypatch)
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("garbage", "fail", "list"))
    assert code == 0
    notes = [n["note"] for n in doc["notes"]]
    assert any(n.startswith("fakemap garbage: output is not JSON") for n in notes), notes
    assert "fakemap fail: exit 3: boom: cannot read the project" in notes, notes  # the first stderr line only
    assert doc["packages"], "the command after the failures still ran"


@requires_git
def test_kbingest_map_mapper_crash_is_a_note_and_the_worktree_goes(pyrepo, tmp_path, monkeypatch):
    install_fake(tmp_path, monkeypatch)

    class Crashing(FakeMapper):
        def map(self, ctx, files):
            raise ValueError("planted")

    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, Crashing("list"))
    assert code == 0
    assert doc["notes"] == [{"language": "fake", "note": "fakemap: mapper failed: ValueError: planted"}]
    assert worktree_count(pyrepo) == 1


@requires_git
def test_kbingest_map_environment_is_network_off(pyrepo, tmp_path, monkeypatch):
    """Planted: a credential and a proxy in the caller's environment, and a harmless variable that must pass."""
    install_fake(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    monkeypatch.setenv("KB_TEST_KEEP", "kept")
    monkeypatch.setenv("http_proxy", "http://proxy.corp.example.com:3128")
    m = FakeMapper("env")
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, m)
    assert code == 0
    env = m.seen["env"]["env"]
    assert env["KB_TEST_API_TOKEN"] is None, "a credential reached the mapper command"
    assert env["KB_TEST_KEEP"] == "kept"
    assert env["http_proxy"] == "http://127.0.0.1:9" and env["HTTPS_PROXY"] == "http://127.0.0.1:9"
    assert env["GOTOOLCHAIN"] == "local" and env["GOPROXY"] == "off"
    assert env["CARGO_NET_OFFLINE"] == "true" and env["npm_config_offline"] == "true"
    files = m.seen["env"]["files"]  # the command ran in the worktree of the commit
    assert "pkg" in files and "a.fake" in files and "uncommitted_mod" not in json.dumps(files)
    assert "planted-token" not in json.dumps(doc)


def test_kbingest_map_scrub_env():
    env = kbingest.scrub_env({"PATH": "/bin", "GITLAB_TOKEN": "t", "AWS_SECRET_ACCESS_KEY": "s", "Https_Proxy": "p",
                              "HOME": "/home/jan.kowalski", "GOTOOLCHAIN": "auto"})
    assert env["PATH"] == "/bin" and env["HOME"] == "/home/jan.kowalski"
    assert "GITLAB_TOKEN" not in env and "AWS_SECRET_ACCESS_KEY" not in env and "Https_Proxy" not in env
    assert env["GOTOOLCHAIN"] == "local"  # offline settings win over the caller's


def test_kbingest_map_notes_are_capped():
    ctx = kbingest.MapCtx("/nowhere", {}, 1, "fake")
    for i in range(kbingest.NOTE_LIMIT + 5):
        ctx.note(f"n{i} /nowhere/x")
    ctx.finish()
    assert len(ctx.notes) == kbingest.NOTE_LIMIT + 1 and ctx.notes[-1] == "5 more notes left out"
    assert ctx.notes[0] == "n0 <worktree>/x"  # the scratch path never reaches the map


@requires_git
def test_kbingest_map_refusals(pyrepo, tmp_path):
    kb = Path(kbingest.kbcommon.KB_DIR)
    code, text = map_run(pyrepo, kb / "public" / "map.json")
    assert code == 2 and "never under kb/" in text and not (kb / "public" / "map.json").exists()
    assert map_run(pyrepo, tmp_path / "x.json", "--lang", "cobol")[0] == 2
    assert map_run(pyrepo, tmp_path / "x.json", "--rev", "no-such-rev")[0] == 2
    assert not (tmp_path / "x.json").exists()
    bad = Repo(tmp_path / "plain")
    Path(bad.path).mkdir()
    assert map_run(bad, tmp_path / "y.json")[0] == 2  # not a repository
    assert worktree_count(pyrepo) == 1


@requires_git
def test_kbingest_map_default_output_is_under_cache_ingest(pyrepo, tmp_path, monkeypatch):
    monkeypatch.setattr(kbingest, "INGEST_CACHE", tmp_path / "_cache" / "ingest")
    monkeypatch.setattr(kbingest, "MAPPERS", [FakeMapper("list", tool="no-such-toolchain-kb")])  # a note, still a map
    assert kbingest.main(["map", pyrepo.path]) == 0
    written = list((tmp_path / "_cache" / "ingest").iterdir())
    assert [p.name for p in written] == [f"deploy-{pyrepo.rev('HEAD')[:12]}.json"]
    assert not kbingest.under_kb(written[0])
    assert kbingest.under_kb(Path(kbingest.kbcommon.KB_DIR) / "public" / "x.json")


def test_kbingest_map_ast_parser_planted_nodes():
    dump = "Module(\n body=[\n  Expr(\n   value=Constant(value='Import(names=[alias(name=\"x\")])')),\n  Import(\n   names=[\n    alias(name='a.b', asname='c')]),\n" \
           "  ImportFrom(\n   module='m',\n   names=[\n    alias(name='n')],\n   level=2)])"
    assert kbingest.ast_imports_and_main(dump) == ({"a.b", "..m"}, False)
    guard = "Module(\n body=[\n  If(\n   test=Compare(\n    left=Name(id='__name__', ctx=Load()),\n    ops=[Eq()],\n    comparators=[\n     Constant(value='__main__')]),\n   body=[\n    Pass()])])"
    assert kbingest.ast_imports_and_main(guard) == (set(), True)
    other = guard.replace("'__main__'", "'other'")
    assert kbingest.ast_imports_and_main(other) == (set(), False)


# ---- Go and Rust mappers: a fake `go` and `cargo` (fixtures/kbingest/fakelang.py) that log every call ----------------

FAKELANG = Path(TOOLS) / "fixtures" / "kbingest" / "fakelang.py"
GO_CALLS = [["version"], ["mod", "edit", "-json"], ["list", "-e", "-json", "./..."]]
CARGO_CALLS = [["--version"], ["metadata", "--format-version", "1", "--no-deps", "--offline", "--locked"]]


@pytest.fixture(scope="module")
def langrepo(tmp_path_factory):
    return commit_files(tmp_path_factory.mktemp("lang") / "svc", {
        "go.mod": "module corp.example.com/app\n\ngo 1.22\n", "main.go": "package main\n",
        "internal/util/u.go": "package util\n", "cmd/tool/main.go": "package main\n",
        "nested/go.mod": "module corp.example.com/nested\n", "nested/x.go": "package nested\n",
        "broken/b.go": "package\n",
        "Cargo.toml": "[workspace]\nmembers = ['crates/*']\n", "src/main.rs": "fn main() {}\n", "src/lib.rs": "",
        "crates/core/Cargo.toml": "[package]\nname = 'core'\n", "crates/core/src/lib.rs": "",
        "tools/Cargo.toml": "[package]\nname = 'tools'\n", "tools/src/main.rs": "fn main() {}\n",
    })


def install_lang(tmp_path, monkeypatch, names=("go", "cargo")):
    """Shims on PATH over fakelang.py, one per NAME; the calls they get are logged to the returned file."""
    bindir = tmp_path / "langbin"
    bindir.mkdir()
    for name in names:
        if os.name == "nt":
            (bindir / f"{name}.cmd").write_text(f'@"{sys.executable}" "{FAKELANG}" {name} %*\r\n', encoding="utf-8",
                                                newline="")
        else:
            shim = bindir / name
            shim.write_text(f'#!/bin/sh\nexec "{sys.executable}" "{FAKELANG}" {name} "$@"\n', encoding="utf-8",
                            newline="\n")
            shim.chmod(0o755)
    log = tmp_path / "calls.jsonl"
    monkeypatch.setenv("PATH", str(bindir) + os.pathsep + os.environ.get("PATH", ""))
    monkeypatch.setenv("KB_FAKE_LOG", str(log))
    monkeypatch.delenv("KB_FAKE_MODE", raising=False)
    return log


def calls_of(log):
    if not log.exists():
        return []
    return [json.loads(ln) for ln in log.read_text(encoding="utf-8").splitlines() if ln.strip()]


def notes_of(doc):
    return [n["note"] for n in doc["notes"]]


@requires_git
def test_kbingest_map_go_runs_the_exact_commands_and_reads_the_stream(langrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    monkeypatch.setenv("HTTPS_PROXY", "http://proxy.corp.example.com:3128")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0
    calls = calls_of(log)
    assert [c["args"] for c in calls] == GO_CALLS  # exactly these argument lists, in this order
    for c in calls:
        assert c["tool"] == "go"
        assert (Path(c["cwd"]).name, Path(c["cwd"]).parent.name.startswith("kbingest-map-")) == ("tree", True)
        assert not Path(c["cwd"]).exists()  # the scratch worktree is gone
        assert c["env"]["GOTOOLCHAIN"] == "local" and c["env"]["GOPROXY"] == "off"
        assert c["env"]["GOFLAGS"] == "-mod=readonly"
        assert c["env"]["KB_TEST_API_TOKEN"] is None and c["env"]["HTTPS_PROXY"] == "http://127.0.0.1:9"
    assert doc["tools"] == {"go": {"tool": "go", "version": "go version go1.22.3 fake/amd64"}}
    app = "corp.example.com/app"
    assert doc["packages"] == [
        {"language": "go", "name": app, "path": ".", "kind": "module", "go": "1.22", "toolchain": "go1.22.3"},
        {"language": "go", "name": app, "path": ".", "module": app},
        {"language": "go", "name": app + "/internal/util", "path": "internal/util", "module": app},
        {"language": "go", "name": app + "/cmd/tool", "path": "cmd/tool", "module": app},
        {"language": "go", "name": app + "/broken", "path": "broken", "module": app},
    ]
    assert doc["imports"] == [
        {"language": "go", "path": "go.mod", "imports": ["corp.example.com/lib", "example.org/x"]},
        {"language": "go", "path": ".", "imports": ["corp.example.com/app/internal/util", "fmt"]},
        {"language": "go", "path": "internal/util", "imports": ["strings"]},
        {"language": "go", "path": "cmd/tool", "imports": ["os"]},
    ]
    assert doc["entry_points"] == [{"language": "go", "path": ".", "kind": "main", "name": app},
                                   {"language": "go", "path": "cmd/tool", "kind": "main", "name": app + "/cmd/tool"}]
    assert notes_of(doc) == ["1 nested go.mod file(s) not mapped (`go list ./...` stays in the root module)",
                             app + "/broken: broken/b.go:1:1: expected 'package'"]  # first line of the package's error
    assert "planted-token" not in json.dumps(doc) and str(tmp_path) not in json.dumps(doc)


@requires_git
def test_kbingest_map_cargo_runs_the_exact_command_and_reads_the_workspace(langrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.CargoMapper())
    assert code == 0
    calls = calls_of(log)
    assert [c["args"] for c in calls] == CARGO_CALLS
    for c in calls:
        assert c["tool"] == "cargo" and Path(c["cwd"]).name == "tree" and not Path(c["cwd"]).exists()
        assert c["env"]["CARGO_NET_OFFLINE"] == "true" and c["env"]["KB_TEST_API_TOKEN"] is None
        assert c["env"]["RUSTUP_AUTO_INSTALL"] == "0", "a rustup cargo proxy must not install a pinned toolchain"
    assert doc["tools"] == {"rust": {"tool": "cargo", "version": "cargo 1.80.0 (fake 2026-01-01)"}}
    assert doc["packages"] == [{"language": "rust", "name": "app", "path": ".", "version": "0.4.0"},
                               {"language": "rust", "name": "core", "path": "crates/core", "version": "0.4.0"}]
    assert doc["imports"] == [{"language": "rust", "path": "Cargo.toml", "imports": ["anyhow", "serde"]}]
    assert doc["entry_points"] == [{"language": "rust", "path": "src/main.rs", "kind": "bin", "name": "app"}]  # not lib
    assert notes_of(doc) == ["1 Cargo.toml file(s) outside the root workspace not mapped"]


@requires_git
def test_kbingest_map_go_and_rust_are_registered_and_selected_by_lang(langrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch)
    out = tmp_path / "both.json"
    assert kbingest.main(["map", langrepo.path, "--out", str(out), "--lang", "go,rust"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert sorted(doc["tools"]) == ["go", "rust"]
    assert [c["args"] for c in calls_of(log)] == GO_CALLS + CARGO_CALLS
    log.unlink()
    assert kbingest.main(["map", langrepo.path, "--out", str(out), "--lang", "rust"]) == 0
    assert [c["tool"] for c in calls_of(log)] == ["cargo", "cargo"]  # --lang rust never starts go


@requires_git
def test_kbingest_map_fake_go_refuses_other_arguments(langrepo, tmp_path, monkeypatch):
    """Planted: a mapper that adds `-deps`, and one that drops `--locked`; the fake exits 64, which proves the exact
    argument lists above are checked by the fake and not merely logged."""
    install_lang(tmp_path, monkeypatch)

    class Deps(kbingest.GoMapper):
        def map(self, ctx, files):
            ctx.json_stream(["go", "list", "-e", "-json", "-deps", "./..."], label="go list -deps")

    class Unlocked(kbingest.CargoMapper):
        def map(self, ctx, files):
            ctx.json(["cargo", "metadata", "--format-version", "1", "--no-deps", "--offline"], label="cargo metadata")

    for mapper, label in ((Deps(), "go list -deps"), (Unlocked(), "cargo metadata")):
        code, doc = fake_map(langrepo, tmp_path, monkeypatch, mapper)
        assert code == 0
        assert any(n.startswith(f"{label}: exit 64: fakelang: unexpected arguments") for n in notes_of(doc)), doc["notes"]


@requires_git
def test_kbingest_map_go_bad_output_is_a_note(langrepo, tmp_path, monkeypatch):
    """Planted: a truncated object after good ones, and an array where the stream should be."""
    install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_FAKE_MODE", "garbage")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0
    assert any(n.startswith("go list -e -json ./...: output is not a JSON stream") for n in notes_of(doc)), doc["notes"]
    assert [p["name"] for p in doc["packages"]] == ["corp.example.com/app"]  # the module; no half-read package list
    monkeypatch.setenv("KB_FAKE_MODE", "array")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert "go list -e -json ./...: a value that is not an object, left out" in notes_of(doc)
    assert doc["entry_points"] == []


@requires_git
def test_kbingest_map_go_package_outside_the_worktree_is_left_out(langrepo, tmp_path, monkeypatch):
    install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_FAKE_MODE", "outside")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0
    assert "example.org/elsewhere: directory outside the worktree, not mapped" in notes_of(doc)
    assert "example.org/elsewhere" not in [p["name"] for p in doc["packages"]]


@requires_git
def test_kbingest_map_go_and_cargo_failures_are_notes(langrepo, tmp_path, monkeypatch):
    """Planted: every command exits 101 (a lock file that would change)."""
    install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_FAKE_MODE", "fail")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.CargoMapper())
    assert code == 0 and doc["packages"] == []
    assert "cargo metadata: exit 101: error: the lock file needs to be updated but --locked was passed" in notes_of(doc)
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0 and doc["packages"] == []
    assert "go mod edit -json: exit 101: error: the lock file needs to be updated but --locked was passed" in notes_of(doc)
    assert any(n.startswith("go list -e -json ./...: exit 101") for n in notes_of(doc))


@requires_git
def test_kbingest_map_go_and_rust_without_a_root_manifest_run_nothing(tmp_path, monkeypatch):
    """Planted: Go and Rust files with no go.mod or Cargo.toml at the root (only a nested one)."""
    log = install_lang(tmp_path, monkeypatch)
    r = commit_files(tmp_path / "loose", {"lib/a.go": "package lib\n", "sub/Cargo.toml": "[package]\n",
                                          "sub/src/lib.rs": ""})
    out = tmp_path / "loose.json"
    assert kbingest.main(["map", r.path, "--out", str(out), "--lang", "go,rust"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert [c["args"] for c in calls_of(log)] == [["version"], ["--version"]]  # only the version of each tool
    assert notes_of(doc) == ["no go.mod or go.work at the repository root: no Go module mapped",
                             "no Cargo.toml at the repository root: no Cargo workspace mapped"]
    assert doc["packages"] == []


@requires_git
def test_kbingest_map_missing_go_and_cargo_are_notes(langrepo, tmp_path, monkeypatch):
    """Planted: a PATH with neither program."""
    empty = tmp_path / "empty"
    empty.mkdir()
    monkeypatch.delenv("KB_FAKE_MODE", raising=False)
    real = kbingest.scrub_env
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(empty)})
    out = tmp_path / "none.json"
    assert kbingest.main(["map", langrepo.path, "--out", str(out), "--lang", "go,rust"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert doc["tools"] == {} and doc["packages"] == []
    assert notes_of(doc) == ["toolchain not installed: go (7 go files not mapped)",
                             "toolchain not installed: cargo (7 rust files not mapped)"]


def lang_ctx(tmp_path):
    return kbingest.MapCtx(tmp_path, kbingest.scrub_env(), 30, "go")


def test_kbingest_map_json_stream_reads_concatenated_values(tmp_path):
    ctx = lang_ctx(tmp_path)
    prog = 'print(\'{"a": 1}{"b": [2]}\\n\\n  [3]\\n\')'
    assert ctx.json_stream([sys.executable, "-c", prog], label="stream") == [{"a": 1}, {"b": [2]}, [3]]
    assert ctx.json_stream([sys.executable, "-c", "pass"], label="empty") == []
    assert ctx.notes == []
    # Planted: a value cut short, and text that is no JSON at all
    assert ctx.json_stream([sys.executable, "-c", 'print(\'{"a": 1} {"b"\')'], label="cut") is None
    assert ctx.json_stream([sys.executable, "-c", "print('go: downloading x')"], label="text") is None
    assert [n.split(" (")[0] for n in ctx.notes] == ["cut: output is not a JSON stream", "text: output is not a JSON stream"]


def test_kbingest_map_rel_keeps_only_paths_inside_the_worktree(tmp_path):
    ctx = lang_ctx(tmp_path)
    assert ctx.rel(str(tmp_path / "a" / "b.go")) == "a/b.go"
    assert ctx.rel(str(tmp_path)) == "."
    assert ctx.rel(str(tmp_path.resolve() / "a")) == "a"
    assert ctx.rel(str(tmp_path.parent / "elsewhere")) is None  # planted: a sibling directory
    assert ctx.rel("") is None and ctx.rel(None) is None


# ---- .NET, Node and TypeScript mappers: fake `dotnet`, `npm`, `tsc` and `npx` (fakelang.py) ------------------------------

WEB_TOOLS = ("dotnet", "npm", "tsc")
MSBUILD_TAIL = ["-getProperty:TargetFrameworkMoniker,LangVersion", "-getItem:PackageReference,ProjectReference"]
PKG_LIST = ["package", "list", "--format", "json", "--no-restore"]
NPM_LS = ["ls", "--all", "--json", "--package-lock-only"]
CSPROJ = '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>\n'
DOTNET_CALLS = [(["--version"], "."),
                (["msbuild", "App.csproj", *MSBUILD_TAIL], "src/App"), (PKG_LIST, "src/App"),
                (["msbuild", "Lib.csproj", *MSBUILD_TAIL], "src/Lib"), (PKG_LIST, "src/Lib"),
                (["msbuild", "A.csproj", *MSBUILD_TAIL], "tools"), (["msbuild", "B.fsproj", *MSBUILD_TAIL], "tools")]
NODE_CALLS = [(["--version"], "."), (NPM_LS, "."), (NPM_LS, "web")]
TSC_CALLS = [(["--version"], "."), (["--showConfig"], "."), (["--listFilesOnly"], "."),
             (["--showConfig"], "web"), (["--listFilesOnly"], "web")]


@pytest.fixture(scope="module")
def webrepo(tmp_path_factory):
    return commit_files(tmp_path_factory.mktemp("web") / "site", {
        "global.json": '{"sdk": {"version": "10.0.100"}}\n',
        "src/App/App.csproj": CSPROJ, "src/App/Program.cs": "class P {}\n",
        "src/Lib/Lib.csproj": CSPROJ, "src/Lib/L.cs": "class L {}\n",
        "tools/A.csproj": CSPROJ, "tools/B.fsproj": CSPROJ, "tools/x.fs": "module X\n",
        "package.json": '{"name": "site"}\n', "package-lock.json": "{}\n",
        "web/package.json": '{"name": "web"}\n', "web/package-lock.json": "{}\n",
        "docs/package.json": '{"name": "docs"}\n',
        "tsconfig.json": "{}\n", "src/a.ts": "export const a = 1;\n",
        "web/tsconfig.json": "{}\n", "web/src/a.ts": "export const b = 2;\n",
        "node_modules/.bin/tsc": "#!/bin/sh\necho the repository's own tsc\n",  # in the tree, never on PATH
    })


def where(call):
    """The directory a logged call ran in, relative to the scratch worktree (`tree`)."""
    parts = Path(call["cwd"]).parts
    top = next(i for i, part in enumerate(parts) if part.startswith("kbingest-map-"))  # .../kbingest-map-X/tree/DIR
    return "/".join(parts[top + 2:]) or "."


def seen(log, tool):
    return [(c["args"], where(c)) for c in calls_of(log) if c["tool"] == tool]


def flags(args):
    return [a.lower() for a in args if a.startswith(("-", "/"))]


@requires_git
def test_kbingest_map_dotnet_runs_the_exact_commands_per_project(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0
    assert seen(log, "dotnet") == DOTNET_CALLS  # exactly these argument lists, each in its project's directory
    for c in calls_of(log):
        assert c["env"]["DOTNET_CLI_TELEMETRY_OPTOUT"] == "1" and c["env"]["MSBUILDDISABLENODEREUSE"] == "1"
        assert c["env"]["KB_TEST_API_TOKEN"] is None and c["env"]["HTTPS_PROXY"] == "http://127.0.0.1:9"
        assert not Path(c["cwd"]).exists()  # the scratch worktree is gone
    for args, _dir in seen(log, "dotnet"):  # never a target, never a restore
        assert not any(f.startswith(("-target", "-t:", "-restore", "-r", "/t", "/restore", "/r")) for f in flags(args))
    assert doc["tools"] == {"dotnet": {"tool": "dotnet", "version": "10.0.100"}}
    app = {"language": "dotnet", "name": "App", "path": "src/App", "project": "src/App/App.csproj", "kind": "project",
           "framework": ".NETCoreApp,Version=v8.0", "langversion": "12.0", "references": ["src/Lib/Lib.csproj"],
           "resolved": {"Newtonsoft.Json": "13.0.1", "Serilog": "3.1.1"}}
    lib = {"language": "dotnet", "name": "Lib", "path": "src/Lib", "project": "src/Lib/Lib.csproj", "kind": "project",
           "framework": ".NETStandard,Version=v2.0"}  # an empty LangVersion and no package: no field
    tool = {"language": "dotnet", "project": "tools/A.csproj", "kind": "project", "path": "tools", "name": "A",
            "framework": ".NETCoreApp,Version=v8.0", "langversion": "12.0", "references": ["Lib/Lib.csproj"]}
    assert doc["packages"] == [app, lib, tool, {**tool, "project": "tools/B.fsproj", "name": "B"}]
    assert doc["imports"][0] == {"language": "dotnet", "path": "src/App/App.csproj",
                                 "imports": ["Newtonsoft.Json", "Serilog"]}
    assert len(doc["imports"]) == 3  # Lib has none
    assert notes_of(doc) == ["tools: 2 project files in one directory, dotnet package list not run"]
    assert "npx" not in {c["tool"] for c in calls_of(log)} and "planted-token" not in json.dumps(doc)


@requires_git
def test_kbingest_map_dotnet_planted_target_restore_and_unpinned_list_are_refused(webrepo, tmp_path, monkeypatch):
    """Planted: a mapper that adds `-target:Build`, one that adds `-restore`, one whose package list may restore, and
    one that names no property; the fake exits 64 for each, so the exact lists above are checked, not merely logged."""
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    bad = {
        "dotnet msbuild -target": ["dotnet", "msbuild", "App.csproj", *MSBUILD_TAIL, "-target:Build"],
        "dotnet msbuild -restore": ["dotnet", "msbuild", "App.csproj", "-restore", *MSBUILD_TAIL],
        "dotnet msbuild -t": ["dotnet", "msbuild", "App.csproj", *MSBUILD_TAIL, "-t:Restore"],
        "dotnet msbuild none": ["dotnet", "msbuild", "App.csproj"],
        "dotnet package list": ["dotnet", "package", "list", "--format", "json"],
        "dotnet build": ["dotnet", "build", "App.csproj", "--no-restore"],
    }
    for label, args in bad.items():
        class Bad(kbingest.DotnetMapper):
            def map(self, ctx, files, args=args, label=label):
                ctx.json(args, label=label, cwd="src/App")

        code, doc = fake_map(webrepo, tmp_path, monkeypatch, Bad())
        assert code == 0
        assert any(n.startswith(f"{label}: exit 64: fakelang: unexpected arguments") for n in notes_of(doc)), (label, doc["notes"])


@requires_git
def test_kbingest_map_dotnet_failures_and_odd_references_are_notes(webrepo, tmp_path, monkeypatch):
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setenv("KB_FAKE_MODE", "noassets")  # no obj/project.assets.json: --no-restore cannot list packages
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0
    assert "dotnet package list (src/App): exit 1: error: No assets file was found for `App.csproj`. Please run restore." \
        in notes_of(doc)
    assert [p["name"] for p in doc["packages"]] == ["App", "Lib", "A", "B"]  # the evaluation still maps each project
    assert all("resolved" not in p for p in doc["packages"])
    monkeypatch.setenv("KB_FAKE_MODE", "outside")  # a ProjectReference that leaves the worktree
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert "src/App/App.csproj: a project reference outside the worktree, left out" in notes_of(doc)
    assert "references" not in doc["packages"][0]
    monkeypatch.setenv("KB_FAKE_MODE", "fail")  # SDK not found, or no such project
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0 and doc["packages"][0]["name"] == "App" and "framework" not in doc["packages"][0]
    assert any(n.startswith("dotnet msbuild src/App/App.csproj: exit 101") for n in notes_of(doc))


@requires_git
def test_kbingest_map_dotnet_cap_and_no_project(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setattr(kbingest, "MAP_MAX_PROJECTS", 1)
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0 and [p["name"] for p in doc["packages"]] == ["App"]
    assert "stopped after 1 projects (3 not mapped)" in notes_of(doc)
    log.unlink()
    loose = commit_files(tmp_path / "loose", {"a.cs": "class A {}\n", "global.json": "{}\n"})
    code, doc = fake_map(loose, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert notes_of(doc) == ["no .csproj, .fsproj or .vbproj file: no .NET project mapped"]
    assert seen(log, "dotnet") == [(["--version"], ".")]  # only the version


@requires_git
def test_kbingest_map_node_runs_npm_ls_with_package_lock_only_and_never_npx(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.NodeMapper())
    assert code == 0
    assert seen(log, "npm") == NODE_CALLS  # only where a package-lock.json sits beside package.json
    for args, _dir in seen(log, "npm")[1:]:
        assert "--package-lock-only" in args
    for c in calls_of(log):
        assert c["env"]["npm_config_offline"] == "true" and c["env"]["npm_config_ignore_scripts"] == "true"
        assert c["env"]["COREPACK_ENABLE_NETWORK"] == "0" and c["env"]["KB_TEST_API_TOKEN"] is None
    assert {c["tool"] for c in calls_of(log)} == {"npm"}  # no npx, no node, no other program
    assert doc["tools"] == {"node": {"tool": "npm", "version": "10.8.2"}}
    web = {"language": "node", "name": "web", "path": "web", "kind": "npm", "version": "1.2.0"}
    assert doc["packages"] == [{**web, "path": "."}, web]
    assert doc["imports"] == [{"language": "node", "path": "package.json", "imports": ["express", "left-pad"]},
                              {"language": "node", "path": "web/package.json", "imports": ["express", "left-pad"]}]
    assert notes_of(doc) == ["1 package.json file(s) without a package-lock.json beside them, npm ls not run"]


@requires_git
def test_kbingest_map_node_reads_the_tree_npm_prints_before_it_exits_1(webrepo, tmp_path, monkeypatch):
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setenv("KB_FAKE_MODE", "problems")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.NodeMapper())
    assert code == 0 and [p["path"] for p in doc["packages"]] == [".", "web"]
    assert "npm ls (web): 1 problem(s), first: missing: ghost@^1.0.0, required by web@1.2.0" in notes_of(doc)
    assert any(n.startswith("npm ls (web): exit 1") for n in notes_of(doc))
    monkeypatch.setenv("KB_FAKE_MODE", "fail")  # exit 101 and nothing on stdout: no tree
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.NodeMapper())
    assert code == 0 and doc["packages"] == []
    assert any(n.startswith("npm ls (.): exit 101") for n in notes_of(doc))


@requires_git
def test_kbingest_map_node_planted_missing_lock_only_and_npx_are_refused(webrepo, tmp_path, monkeypatch):
    """Planted: `npm ls` without --package-lock-only (it would read node_modules), an `npm install`, an `npx tsc` and
    an `npx npm ls`; the fake exits 64 and, for npx, logs the call, which the exact-list tests above prove absent."""
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    bad = {
        "npm ls": ["npm", "ls", "--all", "--json"],
        "npm ls --package-lock": ["npm", "ls", "--all", "--json", "--package-lock"],
        "npm install": ["npm", "install", "--package-lock-only"],
        "npx tsc": ["npx", "tsc", "--showConfig"],
        "npx npm ls": ["npx", "npm", "ls", "--all", "--json", "--package-lock-only"],
    }
    for label, args in bad.items():
        class Bad(kbingest.NodeMapper):
            def map(self, ctx, files, args=args, label=label):
                ctx.json(args, label=label)

        code, doc = fake_map(webrepo, tmp_path, monkeypatch, Bad())
        assert code == 0
        assert any(n.startswith(f"{label}: exit 64: fakelang: unexpected arguments") for n in notes_of(doc)), (label, doc["notes"])
    assert {c["tool"] for c in calls_of(log)} >= {"npx"}  # the planted calls did reach the fake npx and were logged


@requires_git
def test_kbingest_map_typescript_runs_installed_tsc_showconfig_and_listfilesonly(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0
    assert seen(log, "tsc") == TSC_CALLS  # no file on the command line: tsc reads the directory's tsconfig.json
    assert {c["tool"] for c in calls_of(log)} == {"tsc"}  # the repository's node_modules/.bin/tsc and npx never ran
    assert doc["tools"] == {"typescript": {"tool": "tsc", "version": "Version 5.6.2"}}
    root = {"language": "typescript", "name": "tsconfig.json", "path": ".", "kind": "tsconfig", "target": "es2022",
            "module": "esnext", "moduleResolution": "bundler", "strict": True,
            "files": 2}  # the lib file outside the worktree and node_modules/ are not counted
    assert doc["packages"] == [root, {**root, "name": "web/tsconfig.json", "path": "web"}]
    assert doc["imports"] == [] and doc["notes"] == []


@requires_git
def test_kbingest_map_typescript_never_uses_npx_or_the_repositorys_own_tsc(webrepo, tmp_path, monkeypatch):
    """Planted: PATH has no tsc but the worktree carries node_modules/.bin/tsc; and a mapper that goes through npx."""
    log = install_lang(tmp_path, monkeypatch, ("dotnet", "npm", "npx"))  # no tsc shim
    real = kbingest.scrub_env  # and no tsc of the host either: PATH holds the shims only
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(tmp_path / "langbin")})
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0 and doc["packages"] == [] and doc["tools"] == {}
    assert notes_of(doc) == ["toolchain not installed: tsc (4 typescript files not mapped)"]
    assert calls_of(log) == []  # not even an npx fallback

    class ViaNpx(kbingest.TypeScriptMapper):
        def project(self, ctx, cfg):
            ctx.json(["npx", "tsc", "--showConfig"], label="npx tsc --showConfig", cwd=".")

    again = tmp_path / "again"
    again.mkdir()
    install_lang(again, monkeypatch, WEB_TOOLS + ("npx",))
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(again / "langbin")})
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, ViaNpx())
    assert any(n.startswith("npx tsc --showConfig: exit 64") for n in notes_of(doc)), doc["notes"]


@requires_git
def test_kbingest_map_typescript_failures_are_notes(webrepo, tmp_path, monkeypatch):
    """Planted: a tsc that fails (an `extends` it cannot read), and a mapper that puts a file on the command line."""
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setenv("KB_FAKE_MODE", "fail")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0 and doc["packages"] == []
    assert any(n.startswith("tsc --showConfig (web): exit 101") for n in notes_of(doc))
    assert any(n.startswith("tsc --listFilesOnly (.): exit 101") for n in notes_of(doc))
    monkeypatch.delenv("KB_FAKE_MODE")

    class WithFile(kbingest.TypeScriptMapper):
        def project(self, ctx, cfg):
            ctx.json(["tsc", "--showConfig", "src/a.ts"], label="tsc with a file", cwd=".")

    code, doc = fake_map(webrepo, tmp_path, monkeypatch, WithFile())
    assert any(n.startswith("tsc with a file: exit 64") for n in notes_of(doc)), doc["notes"]
    loose = commit_files(tmp_path / "loose", {"a.ts": "export {};\n"})
    code, doc = fake_map(loose, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert notes_of(doc) == ["no tsconfig.json: no TypeScript project mapped"]


@requires_git
def test_kbingest_map_dotnet_node_typescript_are_registered_and_selected_by_lang(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    out = tmp_path / "web.json"
    assert kbingest.main(["map", webrepo.path, "--out", str(out), "--lang", "dotnet,node,typescript"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert sorted(doc["tools"]) == ["dotnet", "node", "typescript"]
    assert [(c["tool"], c["args"], where(c)) for c in calls_of(log)] == \
        [("dotnet", a, d) for a, d in DOTNET_CALLS] + [("npm", a, d) for a, d in NODE_CALLS] + \
        [("tsc", a, d) for a, d in TSC_CALLS]
    log.unlink()
    assert kbingest.main(["map", webrepo.path, "--out", str(out), "--lang", "typescript"]) == 0
    assert {c["tool"] for c in calls_of(log)} == {"tsc"}  # --lang typescript never starts npm or dotnet


@requires_git
def test_kbingest_map_missing_dotnet_npm_and_tsc_are_notes(webrepo, tmp_path, monkeypatch):
    """Planted: a PATH with none of the three programs (nothing is installed for the operator)."""
    empty = tmp_path / "empty"
    empty.mkdir()
    real = kbingest.scrub_env
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(empty)})
    out = tmp_path / "none.json"
    assert kbingest.main(["map", webrepo.path, "--out", str(out), "--lang", "dotnet,node,typescript"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert doc["tools"] == {} and doc["packages"] == []
    assert notes_of(doc) == ["toolchain not installed: dotnet (8 dotnet files not mapped)",
                             "toolchain not installed: npm (3 node files not mapped)",
                             "toolchain not installed: tsc (4 typescript files not mapped)"]


@requires_git
def test_kbingest_map_a_program_inside_the_worktree_is_never_run(webrepo, tmp_path, monkeypatch):
    """Planted: PATH resolves `tsc` to a file under the worktree (as a relative or repository entry would)."""
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    real = kbingest.tool_exe
    monkeypatch.setattr(kbingest, "tool_exe", lambda tool, env, root: (real(tool, env, root)[0], True))
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0 and doc["tools"] == {} and doc["packages"] == []
    assert notes_of(doc) == ["tsc: found inside the worktree, the repository's own program is never run "
                             "(4 typescript files not mapped)"]
    assert calls_of(log) == []


def test_kbingest_map_tool_exe_tells_the_repositorys_program_from_the_installed_one(tmp_path):
    root, outside = tmp_path / "tree", tmp_path / "usr"
    (root / "node_modules" / ".bin").mkdir(parents=True)
    outside.mkdir()
    name = "tsc.cmd" if os.name == "nt" else "tsc"
    for folder in (root / "node_modules" / ".bin", outside):
        (folder / name).write_text("x\n", encoding="utf-8", newline="\n")
        (folder / name).chmod(0o755)
    exe, inside = kbingest.tool_exe("tsc", {"PATH": str(outside)}, root)
    assert exe is not None and inside is False
    exe, inside = kbingest.tool_exe("tsc", {"PATH": str(root / "node_modules" / ".bin")}, root)
    assert exe is not None and inside is True  # planted: the repository's node_modules/.bin on PATH
    assert kbingest.tool_exe("tsc", {"PATH": str(tmp_path / "nowhere")}, root) == (None, False)


@pytest.mark.skipif(os.name == "nt", reason="a relative PATH entry resolves differently on Windows")
def test_kbingest_map_relative_path_entry_is_resolved_against_the_caller_not_the_worktree(tmp_path, monkeypatch):
    """Planted: PATH=bin, and both the caller's directory and the worktree hold bin/probe; only the caller's may run."""
    caller, tree = tmp_path / "caller", tmp_path / "tree"
    for base, text in ((caller, "caller"), (tree, "worktree")):
        (base / "bin").mkdir(parents=True)
        probe = base / "bin" / "probe"
        probe.write_text(f"#!/bin/sh\necho {text}\n", encoding="utf-8", newline="\n")
        probe.chmod(0o755)
    monkeypatch.chdir(caller)
    r = kbingest.run_tool(["probe"], tree, {"PATH": "bin"}, 30)
    assert r.rc == 0 and r.out.strip() == b"caller"
