"""kbingest.py: the survey of a repository before /kb-ingest turns it into facts of a root.

A throwaway repository with planted files: secret files, vendored and generated code (by path, by .gitattributes,
by header), a binary and an oversized file are left out; an unset attribute keeps a file; a secret shape in a kept
file is flagged; an uncommitted change is not read; the pinned urls pass the CODE lint's pinned-source rule; remote
urls lose their credentials; the refusals exit 2.

The map command (`test_kbingest_map_*`): the scratch worktree is removed and holds the commit, not the working tree;
`python -m ast` in a subprocess maps a Python repository (imports, packages, entry points; a file named ast.py is never
run, vendored files are not mapped); a fake toolchain on PATH proves output parsing, the timeout, a missing tool, a bad
exit and output that is not JSON as notes, and that the environment is network-off and drops credentials; a map goes
under _cache/ingest/, never under kb/.

The pins (`test_kbingest_pin_files_*`): a throwaway repository holds every pin file of
kb/public/agents/codebase-mapping.csv, and each parser returns its rows (file, pin, value); comments in global.json,
tsconfig.json and devcontainer.json are scanned out and a .psd1 is scanned as text, never evaluated; lock files the
survey leaves out as generated are still read, vendored ones are not; one malformed file per format is a note and does
not lose the other files' rows; `survey --pins` prints them.
"""
import json, os, subprocess, sys, time
from pathlib import Path

import pytest

from conftest import Repo, TOOLS, git_env, requires_git

import kbfacts, kbid, kbingest

FAKE = Path(TOOLS) / "fixtures" / "kbingest" / "fakemap.py"

TOOL = str(Path(TOOLS) / "kbingest.py")
SECRET_LINE = "pass" + "word: '" + "x" * 12 + "'\n"  # built here so the leak scan of this file stays clean
GO_GEN = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"


def run(*args, cwd=None, env=None):
    p = subprocess.run([sys.executable, TOOL, *args], capture_output=True, text=True, encoding="utf-8",
                       errors="replace", env=env or git_env(), cwd=cwd, timeout=60)
    return p.returncode, p.stdout + p.stderr


@pytest.fixture(scope="module")
def repo(tmp_path_factory):
    r = Repo(tmp_path_factory.mktemp("ingest") / "deploy")
    Path(r.path).mkdir()
    r.git("init", "-q", "-b", "main")
    files = {
        "README.md": "# deploy\n", "src/app.py": "print('hi')\n", "tests/test_app.py": "def test(): pass\n",
        ".gitlab-ci.yml": "stages: [test]\n", "config/app.yaml": "name: deploy\n" + SECRET_LINE,
        ".env": "TOKEN=x\n", ".env.example": "TOKEN=\n", "certs/server.key": "k\n",
        "vendor/lib.js": "x\n", "third_party/kept.py": "x = 1\n", "third_party/other.py": "x = 2\n",
        "package-lock.json": "{}\n", "yarn.lock": "# lock\n", "api/client.py": "x = 3\n", "api/gen.go": GO_GEN,
        "api/keep.go": GO_GEN, "big.txt": "a" * 5000 + "\n",
        ".gitattributes": "api/client.py linguist-generated\nthird_party/kept.py -linguist-vendored\n"
                          "yarn.lock -gitlab-generated\napi/keep.go -linguist-generated\n",
    }
    for rel, text in files.items():
        r.write(rel, text)
    Path(r.file("assets/logo.png")).parent.mkdir(parents=True)
    Path(r.file("assets/logo.png")).write_bytes(b"\x89PNG\0\0\0binary")
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    r.git("remote", "add", "origin", "https://jan.kowalski:tok@gitlab.corp.example.com/ops/deploy.git")
    r.write("src/app.py", SECRET_LINE)  # uncommitted: the survey reads the commit, not the working tree
    return r


@requires_git
def test_survey_leaves_out_and_keeps(repo):
    code, out = run("survey", repo.path, "--files", "--max-bytes", "4000")
    assert code == 0, out
    lines = {tuple(ln.split("\t")[:3]) for ln in out.splitlines() if ln.startswith(("keep\t", "skip\t"))}
    want_skip = {(".env", "secret-file"), ("certs/server.key", "secret-file"), ("vendor/lib.js", "vendored"),
                 ("third_party/other.py", "vendored"), ("package-lock.json", "generated"), ("api/client.py", "generated"),
                 ("api/gen.go", "generated"), ("big.txt", "large"), ("assets/logo.png", "binary")}
    for path, reason in want_skip:
        assert ("skip", reason, path) in lines, (path, out)
    want_keep = {("README.md", "doc"), ("src/app.py", "code"), ("tests/test_app.py", "test"), (".gitlab-ci.yml", "ci"),
                 ("config/app.yaml", "config"), (".env.example", "config"), ("third_party/kept.py", "code"),
                 ("yarn.lock", "other"), ("api/keep.go", "code")}
    for path, kind in want_keep:
        assert ("keep", kind, path) in lines, (path, out)
    secret = [ln for ln in out.splitlines() if ln.startswith("keep\t") and ln.endswith("\tsecret")]
    assert [ln.split("\t")[2] for ln in secret] == ["config/app.yaml"], out  # src/app.py's change is uncommitted
    assert "tok" not in out and "jan.kowalski" not in out, "credentials in the remote url must never be printed"
    assert "remote: origin gitlab.corp.example.com/ops/deploy (forge gitlab)" in out
    assert "on a remote branch: no" in out and "worktree: differs from the commit" in out


@requires_git
def test_pinned_urls_pass_the_code_lint(repo):
    code, url = run("url", repo.path, "src/app.py")
    commit = repo.rev("HEAD")
    assert code == 0 and url.strip() == f"https://gitlab.corp.example.com/ops/deploy/-/raw/{commit}/src/app.py", url
    assert kbfacts.pinned_source({"url": url.strip()})
    assert run("url", repo.path, "no/such.py")[0] == 2


@requires_git
def test_refusals(repo, tmp_path):
    assert run("survey", str(tmp_path))[0] == 2  # not a repository
    assert run("survey", repo.path, "--rev", "no-such-rev")[0] == 2
    bare = Repo(tmp_path / "local")
    Path(bare.path).mkdir()
    bare.git("init", "-q")
    bare.write("a.py", "x = 1\n")
    bare.git("add", "-A")
    bare.git("commit", "-q", "-m", "a")
    code, out = run("url", bare.path, "a.py")
    assert code == 2 and "no pinned url form" in out  # no remote: nothing others could open
    code, out = run("survey", bare.path)
    assert code == 0 and "remote: none" in out


def test_parse_remote_and_forge():
    cases = {
        "git@gitlab.corp.example.com:ops/deploy.git": ("gitlab.corp.example.com", "ops/deploy"),
        "ssh://git@gitlab.corp.example.com:2222/ops/sub/deploy.git": ("gitlab.corp.example.com", "ops/sub/deploy"),
        "https://jan.kowalski:tok@gitlab.corp.example.com:8443/ops/deploy": ("gitlab.corp.example.com:8443", "ops/deploy"),
        "https://github.com/o/r.git": ("github.com", "o/r"),
        "/srv/git/deploy.git": (None, None), "../deploy": (None, None), "C:\\src\\deploy": (None, None),
    }
    for url, want in cases.items():
        assert kbingest.parse_remote(url) == want, url
    assert kbingest.forge_of("github.com") == "github" and kbingest.forge_of("gitlab.com") == "gitlab"
    assert kbingest.forge_of("git.corp.example.com") is None
    assert kbingest.forge_of("git.corp.example.com", "gitlab") == "gitlab"
    assert kbingest.pin_url("github", "github.com", "o/r", "ab" * 20, "a b.py") == \
        f"https://raw.githubusercontent.com/o/r/{'ab' * 20}/a%20b.py"
    assert kbingest.pin_url("github", "ghe.corp.example.com", "o/r", "ab" * 20, "a.py") is None


# ---- map ---------------------------------------------------------------------------------------------------------

def commit_files(path, files):
    r = Repo(path)
    Path(r.path).mkdir(parents=True)
    r.git("init", "-q", "-b", "main")
    for rel, text in files.items():
        r.write(rel, text)
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    return r


@pytest.fixture(scope="module")
def pyrepo(tmp_path_factory):
    r = commit_files(tmp_path_factory.mktemp("map") / "deploy", {
        "pkg/__init__.py": "",
        "pkg/core.py": "import os, sys\nfrom . import util\nfrom pkg.sub import thing as t\nimport a.b as ab\n"
                       "NOTE = 'Import(names=[alias(name=\"in_a_string\")])'\n\ndef main():\n    pass\n",
        "pkg/util.py": "from .. import up\nfrom .sibling import x\n",
        "pkg/sub/__init__.py": "", "pkg/sub/thing.py": "import json\n",
        "pkg/__main__.py": "from pkg import core\ncore.main()\n",
        "src/lib/__init__.py": "", "src/lib/x.py": "import re\n",
        "run.py": "import json\n\nif __name__ == '__main__':\n    print(json.dumps({}))\n",
        "tests/test_run.py": "import pytest\n",
        "broken.py": "def (:\n",
        "ast.py": "raise SystemExit(7)\n",  # `python -m ast` in the worktree root must not run this
        "vendor/lib.py": "import vendored_only\n",
        ".env": "TOKEN=x\n",
        "pyproject.toml": "[project]\nname = 'deploy'\n\n[project.scripts]\ndeploy = 'pkg.core:main'\n",
        "a.fake": "x\n", "b.fake": "y\n",
    })
    r.write("run.py", "import uncommitted_mod\n")  # not committed: the map reads the commit
    return r


def map_run(repo, out, *args, scratch=None):
    env = git_env()
    if scratch is not None:
        env.update(TMPDIR=str(scratch), TEMP=str(scratch), TMP=str(scratch))
    p = subprocess.run([sys.executable, TOOL, "map", repo.path, "--out", str(out), *args], capture_output=True,
                       text=True, encoding="utf-8", errors="replace", env=env, timeout=120)
    return p.returncode, p.stdout + p.stderr


def worktree_count(repo):
    return sum(1 for ln in repo.git("worktree", "list", "--porcelain").splitlines() if ln.startswith("worktree "))


@requires_git
def test_kbingest_map_python_ast_subprocess(pyrepo, tmp_path):
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    out = tmp_path / "deploy.json"
    code, text = map_run(pyrepo, out, "--lang", "python", scratch=scratch)
    assert code == 0, text
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert doc["format"] == 1 and doc["commit"] == pyrepo.rev("HEAD") and doc["repo"] == "deploy"
    assert doc["tools"]["python"]["tool"] == "python" and doc["tools"]["python"]["version"].startswith("Python 3.")
    assert "fake" not in doc["tools"]  # --lang python
    assert {(p["name"], p["path"]) for p in doc["packages"]} == \
        {("pkg", "pkg"), ("pkg.sub", "pkg/sub"), ("lib", "src/lib")}
    imports = {i["path"]: i["imports"] for i in doc["imports"]}
    assert imports["pkg/core.py"] == [".util", "a.b", "os", "pkg.sub", "sys"]  # the string that looks like a node is not one
    assert imports["pkg/util.py"] == ["..up", ".sibling"]
    assert imports["run.py"] == ["json"]  # the commit, not the working tree
    assert "vendored_only" not in json.dumps(doc) and not any(k.startswith("vendor/") for k in imports)
    kinds = {(e["path"], e["kind"]) for e in doc["entry_points"]}
    assert {("run.py", "main-guard"), ("pkg/__main__.py", "module-main")} <= kinds
    assert ("pyproject.toml", "console-script") in kinds
    notes = [n["note"] for n in doc["notes"]]
    assert any(n.startswith("python -m ast broken.py: exit 1") for n in notes), notes  # a syntax error is a note
    assert not any("exit 7" in n for n in notes), "the repository's ast.py ran"
    assert worktree_count(pyrepo) == 1 and list(scratch.iterdir()) == []  # the scratch worktree and its directory are gone
    assert pyrepo.path not in json.dumps(doc) and str(scratch) not in json.dumps(doc)


@requires_git
def test_kbingest_map_planted_ast_shadow_is_not_run(tmp_path):
    """Planted: a repository whose ast.py would print a marker if `-m ast` ran it from the working directory."""
    r = commit_files(tmp_path / "shadow", {"ast.py": "import sys\nsys.stderr.write('SHADOW RAN\\n')\nsys.exit(7)\n",
                                           "m.py": "import os\n"})
    out = tmp_path / "shadow.json"
    code, text = map_run(r, out, "--lang", "python")
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert code == 0 and "SHADOW RAN" not in text + json.dumps(doc), text
    assert {i["path"]: i["imports"] for i in doc["imports"]} == {"ast.py": ["sys"], "m.py": ["os"]}  # parsed, not run


@requires_git
def test_kbingest_map_symlink_is_not_followed(tmp_path):
    outside = tmp_path / "outside.py"
    outside.write_text("import stolen_module\n", encoding="utf-8")
    r = Repo(tmp_path / "links")
    Path(r.path).mkdir()
    r.git("init", "-q", "-b", "main")
    r.write("ok.py", "import os\n")
    try:
        os.symlink(outside, Path(r.path) / "link.py")
    except (OSError, NotImplementedError, AttributeError):
        pytest.skip("symbolic links are not available here")
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    if r.git("ls-files", "-s", "link.py").split()[0] != "120000":
        pytest.skip("git stores no symbolic link here")
    out = tmp_path / "links.json"
    code, text = map_run(r, out)
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert code == 0 and "stolen_module" not in json.dumps(doc), text
    assert any(n["note"].startswith("link.py: not a regular file") for n in doc["notes"]), doc["notes"]


# The fake toolchain: `fakemap` on PATH is a shim over fixtures/kbingest/fakemap.py.

def install_fake(tmp_path, monkeypatch, name="fakemap"):
    bindir = tmp_path / "bin"
    bindir.mkdir(exist_ok=True)
    if os.name == "nt":
        (bindir / f"{name}.cmd").write_text(f'@"{sys.executable}" "{FAKE}" %*\r\n', encoding="utf-8", newline="")
    else:
        shim = bindir / name
        shim.write_text(f'#!/bin/sh\nexec "{sys.executable}" "{FAKE}" "$@"\n', encoding="utf-8", newline="\n")
        shim.chmod(0o755)
    monkeypatch.setenv("PATH", str(bindir) + os.pathsep + os.environ.get("PATH", ""))
    return bindir


class FakeMapper(kbingest.Mapper):
    language = "fake"
    name = "fakemap"
    tool = "fakemap"

    def __init__(self, *steps, tool="fakemap"):
        self.steps, self.tool, self.seen = steps or ("list",), tool, {}

    def files(self, rows):
        return sorted(p for p, _k in rows if p.endswith(".fake"))

    def map(self, ctx, files):
        for step in self.steps:
            data = ctx.json([self.tool, step], label=f"fakemap {step}")
            self.seen[step] = data
            if isinstance(data, dict):
                for pkg in data.get("packages", []):
                    ctx.add_package(pkg["name"], pkg["path"])
                for path, mods in data.get("imports", {}).items():
                    ctx.add_imports(path, mods)
                for ep in data.get("entry_points", []):
                    ctx.add_entry_point(ep["path"], ep["kind"], ep.get("name"))


def fake_map(pyrepo, tmp_path, monkeypatch, mapper, *args):
    monkeypatch.setattr(kbingest, "MAPPERS", [mapper])
    out = tmp_path / "fake.json"
    code = kbingest.main(["map", pyrepo.path, "--out", str(out), *args])
    return code, json.loads(out.read_text(encoding="utf-8"))


@requires_git
def test_kbingest_map_fake_toolchain_output_is_parsed(pyrepo, tmp_path, monkeypatch):
    install_fake(tmp_path, monkeypatch)
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("list"))
    assert code == 0
    assert doc["tools"] == {"fake": {"tool": "fakemap", "version": "fakemap 1.2.3 (fake toolchain)"}}
    assert doc["packages"] == [{"language": "fake", "name": "app", "path": "src"}]
    assert doc["imports"] == [{"language": "fake", "path": "src/a.fake", "imports": ["x", "y"]}]  # sorted, de-duplicated
    assert doc["entry_points"] == [{"language": "fake", "path": "src/a.fake", "kind": "main", "name": "app"}]
    assert doc["notes"] == []  # an unknown field in the tool's output is ignored, not a note


@requires_git
def test_kbingest_map_fake_toolchain_timeout_is_a_note(pyrepo, tmp_path, monkeypatch):
    """Planted: a tool that sleeps 60 s under --timeout 2."""
    install_fake(tmp_path, monkeypatch)
    started = time.monotonic()
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("sleep", "list"), "--timeout", "2")
    assert time.monotonic() - started < 40
    assert code == 0
    assert {"language": "fake", "note": "fakemap sleep: timed out after 2s"} in doc["notes"], doc["notes"]
    assert doc["packages"] and doc["imports"], "the next command still ran after the timeout"
    assert worktree_count(pyrepo) == 1


@requires_git
def test_kbingest_map_missing_toolchain_is_a_note(pyrepo, tmp_path, monkeypatch):
    """Planted: a mapper whose program is on no PATH."""
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("list", tool="no-such-toolchain-kb"))
    assert code == 0, "a missing toolchain is a note, not an error"
    assert doc["tools"] == {} and doc["packages"] == [] and doc["imports"] == []
    assert doc["notes"] == [{"language": "fake",
                             "note": "toolchain not installed: fakemap (2 fake files not mapped)"}]


@requires_git
def test_kbingest_map_bad_output_and_exit_are_notes(pyrepo, tmp_path, monkeypatch):
    """Planted: output that is not JSON, and a non-zero exit with a stderr message."""
    install_fake(tmp_path, monkeypatch)
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, FakeMapper("garbage", "fail", "list"))
    assert code == 0
    notes = [n["note"] for n in doc["notes"]]
    assert any(n.startswith("fakemap garbage: output is not JSON") for n in notes), notes
    assert "fakemap fail: exit 3: boom: cannot read the project" in notes, notes  # the first stderr line only
    assert doc["packages"], "the command after the failures still ran"


@requires_git
def test_kbingest_map_mapper_crash_is_a_note_and_the_worktree_goes(pyrepo, tmp_path, monkeypatch):
    install_fake(tmp_path, monkeypatch)

    class Crashing(FakeMapper):
        def map(self, ctx, files):
            raise ValueError("planted")

    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, Crashing("list"))
    assert code == 0
    assert doc["notes"] == [{"language": "fake", "note": "fakemap: mapper failed: ValueError: planted"}]
    assert worktree_count(pyrepo) == 1


@requires_git
def test_kbingest_map_environment_is_network_off(pyrepo, tmp_path, monkeypatch):
    """Planted: a credential and a proxy in the caller's environment, and a harmless variable that must pass."""
    install_fake(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    monkeypatch.setenv("KB_TEST_KEEP", "kept")
    monkeypatch.setenv("http_proxy", "http://proxy.corp.example.com:3128")
    m = FakeMapper("env")
    code, doc = fake_map(pyrepo, tmp_path, monkeypatch, m)
    assert code == 0
    env = m.seen["env"]["env"]
    assert env["KB_TEST_API_TOKEN"] is None, "a credential reached the mapper command"
    assert env["KB_TEST_KEEP"] == "kept"
    assert env["http_proxy"] == "http://127.0.0.1:9" and env["HTTPS_PROXY"] == "http://127.0.0.1:9"
    assert env["GOTOOLCHAIN"] == "local" and env["GOPROXY"] == "off"
    assert env["CARGO_NET_OFFLINE"] == "true" and env["npm_config_offline"] == "true"
    files = m.seen["env"]["files"]  # the command ran in the worktree of the commit
    assert "pkg" in files and "a.fake" in files and "uncommitted_mod" not in json.dumps(files)
    assert "planted-token" not in json.dumps(doc)


def test_kbingest_map_scrub_env():
    env = kbingest.scrub_env({"PATH": "/bin", "GITLAB_TOKEN": "t", "AWS_SECRET_ACCESS_KEY": "s", "Https_Proxy": "p",
                              "HOME": "/home/jan.kowalski", "GOTOOLCHAIN": "auto"})
    assert env["PATH"] == "/bin" and env["HOME"] == "/home/jan.kowalski"
    assert "GITLAB_TOKEN" not in env and "AWS_SECRET_ACCESS_KEY" not in env and "Https_Proxy" not in env
    assert env["GOTOOLCHAIN"] == "local"  # offline settings win over the caller's


def test_kbingest_map_windows_no_cwd_lookup():
    """On Windows cmd.exe (an npm cmd-shim) finds a bare `node` in its working folder, the repository's, unless
    NoDefaultCurrentDirectoryInExePath exists; scrub_env sets it there, and only there by default."""
    base = {"PATH": "/bin"}
    assert kbingest.scrub_env(base, windows=True)["NoDefaultCurrentDirectoryInExePath"] == "1"
    assert kbingest.scrub_env({**base, "NoDefaultCurrentDirectoryInExePath": ""}, windows=True)[
        "NoDefaultCurrentDirectoryInExePath"] == "1"
    assert "NoDefaultCurrentDirectoryInExePath" not in kbingest.scrub_env(base, windows=False)
    assert ("NoDefaultCurrentDirectoryInExePath" in kbingest.scrub_env(base)) == (os.name == "nt")


def test_kbingest_map_notes_are_capped():
    ctx = kbingest.MapCtx("/nowhere", {}, 1, "fake")
    for i in range(kbingest.NOTE_LIMIT + 5):
        ctx.note(f"n{i} /nowhere/x")
    ctx.finish()
    assert len(ctx.notes) == kbingest.NOTE_LIMIT + 1 and ctx.notes[-1] == "5 more notes left out"
    assert ctx.notes[0] == "n0 <worktree>/x"  # the scratch path never reaches the map


@requires_git
def test_kbingest_map_refusals(pyrepo, tmp_path):
    kb = Path(kbingest.kbcommon.KB_DIR)
    code, text = map_run(pyrepo, kb / "public" / "map.json")
    assert code == 2 and "never under kb/" in text and not (kb / "public" / "map.json").exists()
    assert map_run(pyrepo, tmp_path / "x.json", "--lang", "cobol")[0] == 2
    assert map_run(pyrepo, tmp_path / "x.json", "--rev", "no-such-rev")[0] == 2
    assert not (tmp_path / "x.json").exists()
    bad = Repo(tmp_path / "plain")
    Path(bad.path).mkdir()
    assert map_run(bad, tmp_path / "y.json")[0] == 2  # not a repository
    assert worktree_count(pyrepo) == 1


@requires_git
def test_kbingest_map_default_output_is_under_cache_ingest(pyrepo, tmp_path, monkeypatch):
    monkeypatch.setattr(kbingest, "INGEST_CACHE", tmp_path / "_cache" / "ingest")
    monkeypatch.setattr(kbingest, "MAPPERS", [FakeMapper("list", tool="no-such-toolchain-kb")])  # a note, still a map
    assert kbingest.main(["map", pyrepo.path]) == 0
    written = list((tmp_path / "_cache" / "ingest").iterdir())
    assert [p.name for p in written] == [f"deploy-{pyrepo.rev('HEAD')[:12]}.json"]
    assert not kbingest.under_kb(written[0])
    assert kbingest.under_kb(Path(kbingest.kbcommon.KB_DIR) / "public" / "x.json")


def test_kbingest_map_ast_parser_planted_nodes():
    dump = "Module(\n body=[\n  Expr(\n   value=Constant(value='Import(names=[alias(name=\"x\")])')),\n  Import(\n   names=[\n    alias(name='a.b', asname='c')]),\n" \
           "  ImportFrom(\n   module='m',\n   names=[\n    alias(name='n')],\n   level=2)])"
    assert kbingest.ast_imports_and_main(dump) == ({"a.b", "..m"}, False)
    guard = "Module(\n body=[\n  If(\n   test=Compare(\n    left=Name(id='__name__', ctx=Load()),\n    ops=[Eq()],\n    comparators=[\n     Constant(value='__main__')]),\n   body=[\n    Pass()])])"
    assert kbingest.ast_imports_and_main(guard) == (set(), True)
    other = guard.replace("'__main__'", "'other'")
    assert kbingest.ast_imports_and_main(other) == (set(), False)


# ---- Go and Rust mappers: a fake `go` and `cargo` (fixtures/kbingest/fakelang.py) that log every call ----------------

FAKELANG = Path(TOOLS) / "fixtures" / "kbingest" / "fakelang.py"
GO_CALLS = [["version"], ["mod", "edit", "-json"], ["list", "-e", "-json", "./..."]]
CARGO_CALLS = [["--version"], ["metadata", "--format-version", "1", "--no-deps", "--offline", "--locked"]]


@pytest.fixture(scope="module")
def langrepo(tmp_path_factory):
    return commit_files(tmp_path_factory.mktemp("lang") / "svc", {
        "go.mod": "module corp.example.com/app\n\ngo 1.22\n", "main.go": "package main\n",
        "internal/util/u.go": "package util\n", "cmd/tool/main.go": "package main\n",
        "nested/go.mod": "module corp.example.com/nested\n", "nested/x.go": "package nested\n",
        "broken/b.go": "package\n",
        "Cargo.toml": "[workspace]\nmembers = ['crates/*']\n", "src/main.rs": "fn main() {}\n", "src/lib.rs": "",
        "crates/core/Cargo.toml": "[package]\nname = 'core'\n", "crates/core/src/lib.rs": "",
        "tools/Cargo.toml": "[package]\nname = 'tools'\n", "tools/src/main.rs": "fn main() {}\n",
    })


def install_lang(tmp_path, monkeypatch, names=("go", "cargo")):
    """Shims on PATH over fakelang.py, one per NAME; the calls they get are logged to the returned file."""
    bindir = tmp_path / "langbin"
    bindir.mkdir()
    for name in names:
        if os.name == "nt":
            (bindir / f"{name}.cmd").write_text(f'@"{sys.executable}" "{FAKELANG}" {name} %*\r\n', encoding="utf-8",
                                                newline="")
        else:
            shim = bindir / name
            shim.write_text(f'#!/bin/sh\nexec "{sys.executable}" "{FAKELANG}" {name} "$@"\n', encoding="utf-8",
                            newline="\n")
            shim.chmod(0o755)
    log = tmp_path / "calls.jsonl"
    monkeypatch.setenv("PATH", str(bindir) + os.pathsep + os.environ.get("PATH", ""))
    monkeypatch.setenv("KB_FAKE_LOG", str(log))
    monkeypatch.delenv("KB_FAKE_MODE", raising=False)
    return log


def calls_of(log):
    if not log.exists():
        return []
    return [json.loads(ln) for ln in log.read_text(encoding="utf-8").splitlines() if ln.strip()]


def notes_of(doc):
    return [n["note"] for n in doc["notes"]]


@requires_git
def test_kbingest_map_go_runs_the_exact_commands_and_reads_the_stream(langrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    monkeypatch.setenv("HTTPS_PROXY", "http://proxy.corp.example.com:3128")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0
    calls = calls_of(log)
    assert [c["args"] for c in calls] == GO_CALLS  # exactly these argument lists, in this order
    for c in calls:
        assert c["tool"] == "go"
        assert (Path(c["cwd"]).name, Path(c["cwd"]).parent.name.startswith("kbingest-map-")) == ("tree", True)
        assert not Path(c["cwd"]).exists()  # the scratch worktree is gone
        assert c["env"]["GOTOOLCHAIN"] == "local" and c["env"]["GOPROXY"] == "off"
        assert c["env"]["GOFLAGS"] == "-mod=readonly"
        assert c["env"]["KB_TEST_API_TOKEN"] is None and c["env"]["HTTPS_PROXY"] == "http://127.0.0.1:9"
    assert doc["tools"] == {"go": {"tool": "go", "version": "go version go1.22.3 fake/amd64"}}
    app = "corp.example.com/app"
    assert doc["packages"] == [
        {"language": "go", "name": app, "path": ".", "kind": "module", "go": "1.22", "toolchain": "go1.22.3"},
        {"language": "go", "name": app, "path": ".", "module": app},
        {"language": "go", "name": app + "/internal/util", "path": "internal/util", "module": app},
        {"language": "go", "name": app + "/cmd/tool", "path": "cmd/tool", "module": app},
        {"language": "go", "name": app + "/broken", "path": "broken", "module": app},
    ]
    assert doc["imports"] == [
        {"language": "go", "path": "go.mod", "imports": ["corp.example.com/lib", "example.org/x"]},
        {"language": "go", "path": ".", "imports": ["corp.example.com/app/internal/util", "fmt"]},
        {"language": "go", "path": "internal/util", "imports": ["strings"]},
        {"language": "go", "path": "cmd/tool", "imports": ["os"]},
    ]
    assert doc["entry_points"] == [{"language": "go", "path": ".", "kind": "main", "name": app},
                                   {"language": "go", "path": "cmd/tool", "kind": "main", "name": app + "/cmd/tool"}]
    assert notes_of(doc) == ["1 nested go.mod file(s) not mapped (`go list ./...` stays in the root module)",
                             app + "/broken: broken/b.go:1:1: expected 'package'"]  # first line of the package's error
    assert "planted-token" not in json.dumps(doc) and str(tmp_path) not in json.dumps(doc)


@requires_git
def test_kbingest_map_cargo_runs_the_exact_command_and_reads_the_workspace(langrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.CargoMapper())
    assert code == 0
    calls = calls_of(log)
    assert [c["args"] for c in calls] == CARGO_CALLS
    for c in calls:
        assert c["tool"] == "cargo" and Path(c["cwd"]).name == "tree" and not Path(c["cwd"]).exists()
        assert c["env"]["CARGO_NET_OFFLINE"] == "true" and c["env"]["KB_TEST_API_TOKEN"] is None
        assert c["env"]["RUSTUP_AUTO_INSTALL"] == "0", "a rustup cargo proxy must not install a pinned toolchain"
    assert doc["tools"] == {"rust": {"tool": "cargo", "version": "cargo 1.80.0 (fake 2026-01-01)"}}
    assert doc["packages"] == [{"language": "rust", "name": "app", "path": ".", "version": "0.4.0"},
                               {"language": "rust", "name": "core", "path": "crates/core", "version": "0.4.0"}]
    assert doc["imports"] == [{"language": "rust", "path": "Cargo.toml", "imports": ["anyhow", "serde"]}]
    assert doc["entry_points"] == [{"language": "rust", "path": "src/main.rs", "kind": "bin", "name": "app"}]  # not lib
    assert notes_of(doc) == ["1 Cargo.toml file(s) outside the root workspace not mapped"]


@requires_git
def test_kbingest_map_go_and_rust_are_registered_and_selected_by_lang(langrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch)
    out = tmp_path / "both.json"
    assert kbingest.main(["map", langrepo.path, "--out", str(out), "--lang", "go,rust"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert sorted(doc["tools"]) == ["go", "rust"]
    assert [c["args"] for c in calls_of(log)] == GO_CALLS + CARGO_CALLS
    log.unlink()
    assert kbingest.main(["map", langrepo.path, "--out", str(out), "--lang", "rust"]) == 0
    assert [c["tool"] for c in calls_of(log)] == ["cargo", "cargo"]  # --lang rust never starts go


@requires_git
def test_kbingest_map_fake_go_refuses_other_arguments(langrepo, tmp_path, monkeypatch):
    """Planted: a mapper that adds `-deps`, and one that drops `--locked`; the fake exits 64, which proves the exact
    argument lists above are checked by the fake and not merely logged."""
    install_lang(tmp_path, monkeypatch)

    class Deps(kbingest.GoMapper):
        def map(self, ctx, files):
            ctx.json_stream(["go", "list", "-e", "-json", "-deps", "./..."], label="go list -deps")

    class Unlocked(kbingest.CargoMapper):
        def map(self, ctx, files):
            ctx.json(["cargo", "metadata", "--format-version", "1", "--no-deps", "--offline"], label="cargo metadata")

    for mapper, label in ((Deps(), "go list -deps"), (Unlocked(), "cargo metadata")):
        code, doc = fake_map(langrepo, tmp_path, monkeypatch, mapper)
        assert code == 0
        assert any(n.startswith(f"{label}: exit 64: fakelang: unexpected arguments") for n in notes_of(doc)), doc["notes"]


@requires_git
def test_kbingest_map_go_bad_output_is_a_note(langrepo, tmp_path, monkeypatch):
    """Planted: a truncated object after good ones, and an array where the stream should be."""
    install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_FAKE_MODE", "garbage")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0
    assert any(n.startswith("go list -e -json ./...: output is not a JSON stream") for n in notes_of(doc)), doc["notes"]
    assert [p["name"] for p in doc["packages"]] == ["corp.example.com/app"]  # the module; no half-read package list
    monkeypatch.setenv("KB_FAKE_MODE", "array")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert "go list -e -json ./...: a value that is not an object, left out" in notes_of(doc)
    assert doc["entry_points"] == []


@requires_git
def test_kbingest_map_go_package_outside_the_worktree_is_left_out(langrepo, tmp_path, monkeypatch):
    install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_FAKE_MODE", "outside")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0
    assert "example.org/elsewhere: directory outside the worktree, not mapped" in notes_of(doc)
    assert "example.org/elsewhere" not in [p["name"] for p in doc["packages"]]


@requires_git
def test_kbingest_map_go_and_cargo_failures_are_notes(langrepo, tmp_path, monkeypatch):
    """Planted: every command exits 101 (a lock file that would change)."""
    install_lang(tmp_path, monkeypatch)
    monkeypatch.setenv("KB_FAKE_MODE", "fail")
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.CargoMapper())
    assert code == 0 and doc["packages"] == []
    assert "cargo metadata: exit 101: error: the lock file needs to be updated but --locked was passed" in notes_of(doc)
    code, doc = fake_map(langrepo, tmp_path, monkeypatch, kbingest.GoMapper())
    assert code == 0 and doc["packages"] == []
    assert "go mod edit -json: exit 101: error: the lock file needs to be updated but --locked was passed" in notes_of(doc)
    assert any(n.startswith("go list -e -json ./...: exit 101") for n in notes_of(doc))


@requires_git
def test_kbingest_map_go_and_rust_without_a_root_manifest_run_nothing(tmp_path, monkeypatch):
    """Planted: Go and Rust files with no go.mod or Cargo.toml at the root (only a nested one)."""
    log = install_lang(tmp_path, monkeypatch)
    r = commit_files(tmp_path / "loose", {"lib/a.go": "package lib\n", "sub/Cargo.toml": "[package]\n",
                                          "sub/src/lib.rs": ""})
    out = tmp_path / "loose.json"
    assert kbingest.main(["map", r.path, "--out", str(out), "--lang", "go,rust"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert [c["args"] for c in calls_of(log)] == [["version"], ["--version"]]  # only the version of each tool
    assert notes_of(doc) == ["no go.mod or go.work at the repository root: no Go module mapped",
                             "no Cargo.toml at the repository root: no Cargo workspace mapped"]
    assert doc["packages"] == []


@requires_git
def test_kbingest_map_missing_go_and_cargo_are_notes(langrepo, tmp_path, monkeypatch):
    """Planted: a PATH with neither program."""
    empty = tmp_path / "empty"
    empty.mkdir()
    monkeypatch.delenv("KB_FAKE_MODE", raising=False)
    real = kbingest.scrub_env
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(empty)})
    out = tmp_path / "none.json"
    assert kbingest.main(["map", langrepo.path, "--out", str(out), "--lang", "go,rust"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert doc["tools"] == {} and doc["packages"] == []
    assert notes_of(doc) == ["toolchain not installed: go (7 go files not mapped)",
                             "toolchain not installed: cargo (7 rust files not mapped)"]


def lang_ctx(tmp_path):
    return kbingest.MapCtx(tmp_path, kbingest.scrub_env(), 30, "go")


def test_kbingest_map_json_stream_reads_concatenated_values(tmp_path):
    ctx = lang_ctx(tmp_path)
    prog = 'print(\'{"a": 1}{"b": [2]}\\n\\n  [3]\\n\')'
    assert ctx.json_stream([sys.executable, "-c", prog], label="stream") == [{"a": 1}, {"b": [2]}, [3]]
    assert ctx.json_stream([sys.executable, "-c", "pass"], label="empty") == []
    assert ctx.notes == []
    # Planted: a value cut short, and text that is no JSON at all
    assert ctx.json_stream([sys.executable, "-c", 'print(\'{"a": 1} {"b"\')'], label="cut") is None
    assert ctx.json_stream([sys.executable, "-c", "print('go: downloading x')"], label="text") is None
    assert [n.split(" (")[0] for n in ctx.notes] == ["cut: output is not a JSON stream", "text: output is not a JSON stream"]


def test_kbingest_map_rel_keeps_only_paths_inside_the_worktree(tmp_path):
    ctx = lang_ctx(tmp_path)
    assert ctx.rel(str(tmp_path / "a" / "b.go")) == "a/b.go"
    assert ctx.rel(str(tmp_path)) == "."
    assert ctx.rel(str(tmp_path.resolve() / "a")) == "a"
    assert ctx.rel(str(tmp_path.parent / "elsewhere")) is None  # planted: a sibling directory
    assert ctx.rel("") is None and ctx.rel(None) is None


# ---- .NET, Node and TypeScript mappers: fake `dotnet`, `npm`, `tsc` and `npx` (fakelang.py) ------------------------------

WEB_TOOLS = ("dotnet", "npm", "tsc")
MSBUILD_TAIL = ["-getProperty:TargetFrameworkMoniker,LangVersion", "-getItem:PackageReference,ProjectReference"]
NO_RSP = "-noAutoResponse"  # no Directory.Build.rsp of the repository adds switches
PKG_LIST = ["package", "list", "--format", "json", "--no-restore"]
NPM_LS = ["ls", "--all", "--json", "--package-lock-only"]
CSPROJ = '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>\n'
DOTNET_CALLS = [(["--version"], "."),
                (["msbuild", NO_RSP, "App.csproj", *MSBUILD_TAIL], "src/App"), (PKG_LIST, "src/App"),
                (["msbuild", NO_RSP, "Lib.csproj", *MSBUILD_TAIL], "src/Lib"), (PKG_LIST, "src/Lib"),
                (["msbuild", NO_RSP, "A.csproj", *MSBUILD_TAIL], "tools"),
                (["msbuild", NO_RSP, "B.fsproj", *MSBUILD_TAIL], "tools")]
NODE_CALLS = [(["--version"], "."), (NPM_LS, "."), (NPM_LS, "web")]
TSC_CALLS = [(["--version"], "."), (["--showConfig"], "."), (["--listFilesOnly"], "."),
             (["--showConfig"], "web"), (["--listFilesOnly"], "web")]


@pytest.fixture(scope="module")
def webrepo(tmp_path_factory):
    return commit_files(tmp_path_factory.mktemp("web") / "site", {
        "global.json": '{"sdk": {"version": "10.0.100"}}\n',
        "src/App/App.csproj": CSPROJ, "src/App/Program.cs": "class P {}\n",
        "src/Lib/Lib.csproj": CSPROJ, "src/Lib/L.cs": "class L {}\n",
        "tools/A.csproj": CSPROJ, "tools/B.fsproj": CSPROJ, "tools/x.fs": "module X\n",
        "package.json": '{"name": "site"}\n', "package-lock.json": "{}\n",
        "web/package.json": '{"name": "web"}\n', "web/package-lock.json": "{}\n",
        "docs/package.json": '{"name": "docs"}\n',
        "tsconfig.json": "{}\n", "src/a.ts": "export const a = 1;\n",
        "web/tsconfig.json": "{}\n", "web/src/a.ts": "export const b = 2;\n",
        "node_modules/.bin/tsc": "#!/bin/sh\necho the repository's own tsc\n",  # in the tree, never on PATH
    })


def where(call):
    """The directory a logged call ran in, relative to the scratch worktree (`tree`)."""
    parts = Path(call["cwd"]).parts
    top = next(i for i, part in enumerate(parts) if part.startswith("kbingest-map-"))  # .../kbingest-map-X/tree/DIR
    return "/".join(parts[top + 2:]) or "."


def seen(log, tool):
    return [(c["args"], where(c)) for c in calls_of(log) if c["tool"] == tool]


def flags(args):
    return [a.lower() for a in args if a.startswith(("-", "/"))]


@requires_git
def test_kbingest_map_dotnet_runs_the_exact_commands_per_project(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0
    assert seen(log, "dotnet") == DOTNET_CALLS  # exactly these argument lists, each in its project's directory
    for c in calls_of(log):
        assert c["env"]["DOTNET_CLI_TELEMETRY_OPTOUT"] == "1" and c["env"]["MSBUILDDISABLENODEREUSE"] == "1"
        assert c["env"]["KB_TEST_API_TOKEN"] is None and c["env"]["HTTPS_PROXY"] == "http://127.0.0.1:9"
        assert not Path(c["cwd"]).exists()  # the scratch worktree is gone
    for args, _dir in seen(log, "dotnet"):  # never a target, never a restore
        assert not any(f.startswith(("-target", "-t:", "-restore", "-r", "/t", "/restore", "/r")) for f in flags(args))
    assert doc["tools"] == {"dotnet": {"tool": "dotnet", "version": "10.0.100"}}
    app = {"language": "dotnet", "name": "App", "path": "src/App", "project": "src/App/App.csproj", "kind": "project",
           "framework": ".NETCoreApp,Version=v8.0", "langversion": "12.0", "references": ["src/Lib/Lib.csproj"],
           "resolved": {"Newtonsoft.Json": "13.0.1", "Serilog": "3.1.1"}}
    lib = {"language": "dotnet", "name": "Lib", "path": "src/Lib", "project": "src/Lib/Lib.csproj", "kind": "project",
           "framework": ".NETStandard,Version=v2.0"}  # an empty LangVersion and no package: no field
    tool = {"language": "dotnet", "project": "tools/A.csproj", "kind": "project", "path": "tools", "name": "A",
            "framework": ".NETCoreApp,Version=v8.0", "langversion": "12.0", "references": ["Lib/Lib.csproj"]}
    assert doc["packages"] == [app, lib, tool, {**tool, "project": "tools/B.fsproj", "name": "B"}]
    assert doc["imports"][0] == {"language": "dotnet", "path": "src/App/App.csproj",
                                 "imports": ["Newtonsoft.Json", "Serilog"]}
    assert len(doc["imports"]) == 3  # Lib has none
    assert notes_of(doc) == ["tools: 2 project files in one directory, dotnet package list not run"]
    assert "npx" not in {c["tool"] for c in calls_of(log)} and "planted-token" not in json.dumps(doc)


@requires_git
def test_kbingest_map_dotnet_planted_target_restore_and_unpinned_list_are_refused(webrepo, tmp_path, monkeypatch):
    """Planted: a mapper that adds `-target:Build`, one that adds `-restore`, one whose package list may restore, one
    that names no property, and one that lets a Directory.Build.rsp apply; the fake exits 64 for each, so the exact lists above are checked, not merely logged."""
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    bad = {
        "dotnet msbuild -target": ["dotnet", "msbuild", NO_RSP, "App.csproj", *MSBUILD_TAIL, "-target:Build"],
        "dotnet msbuild -restore": ["dotnet", "msbuild", NO_RSP, "App.csproj", "-restore", *MSBUILD_TAIL],
        "dotnet msbuild -t": ["dotnet", "msbuild", NO_RSP, "App.csproj", *MSBUILD_TAIL, "-t:Restore"],
        "dotnet msbuild none": ["dotnet", "msbuild", NO_RSP, "App.csproj"],
        "dotnet msbuild with rsp": ["dotnet", "msbuild", "App.csproj", *MSBUILD_TAIL],
        "dotnet package list": ["dotnet", "package", "list", "--format", "json"],
        "dotnet build": ["dotnet", "build", "App.csproj", "--no-restore"],
    }
    for label, args in bad.items():
        class Bad(kbingest.DotnetMapper):
            def map(self, ctx, files, args=args, label=label):
                ctx.json(args, label=label, cwd="src/App")

        code, doc = fake_map(webrepo, tmp_path, monkeypatch, Bad())
        assert code == 0
        assert any(n.startswith(f"{label}: exit 64: fakelang: unexpected arguments") for n in notes_of(doc)), (label, doc["notes"])


@requires_git
def test_kbingest_map_dotnet_no_auto_response(tmp_path, monkeypatch):
    """Planted: a Directory.Build.rsp at the root and one in the project's folder, each adding -target, -restore and
    -logger. MSBuild reads them by itself unless -noAutoResponse is passed, so every msbuild call carries it."""
    log = install_lang(tmp_path, monkeypatch, ("dotnet",))
    rsp = "-target:Build\n-restore\n-logger:FileLogger,Microsoft.Build;logfile=out.log\n"
    r = commit_files(tmp_path / "rsp", {"Directory.Build.rsp": rsp, "src/App/Directory.Build.rsp": rsp,
                                        "src/App/App.csproj": CSPROJ, "src/App/Program.cs": "class P {}\n"})
    code, doc = fake_map(r, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0
    assert seen(log, "dotnet") == [(["--version"], "."), (["msbuild", NO_RSP, "App.csproj", *MSBUILD_TAIL], "src/App"),
                                   (PKG_LIST, "src/App")]
    assert doc["packages"][0]["framework"] == ".NETCoreApp,Version=v8.0"  # the fake answered the exact list
    assert not any("exit 64" in n for n in notes_of(doc)), doc["notes"]


@requires_git
def test_kbingest_map_dotnet_sdk_paths(tmp_path, monkeypatch):
    """Planted: a global.json (with comments) that sets sdk.paths, once in a project's parent folder and once at the
    root; a .NET 10 host would load an SDK from the worktree, so no dotnet command runs, not even the version."""
    log = install_lang(tmp_path, monkeypatch, ("dotnet",))
    paths = '{\n  // the SDK of the repository\n  "sdk": {"version": "10.0.100", "paths": [".dotnet", "$host$"],},\n}\n'
    for name, where_ in (("nested", "src/global.json"), ("top", "global.json")):
        r = commit_files(tmp_path / name, {"global.json": '{"sdk": {"version": "10.0.100"}}\n', where_: paths,
                                           "src/App/App.csproj": CSPROJ, "src/App/Program.cs": "class P {}\n"})
        code, doc = fake_map(r, tmp_path, monkeypatch, kbingest.DotnetMapper())
        assert code == 0
        assert calls_of(log) == [], name  # not even dotnet --version
        assert notes_of(doc) == [f"{where_}: sets sdk.paths (an SDK from folders it names), .NET not mapped and no "
                                 "dotnet command run"]
        assert doc["tools"] == {} and doc["packages"] == []
    bad = commit_files(tmp_path / "bad", {"global.json": '{"sdk": {"paths": [".dotnet"]\n',  # unterminated: declines
                                          "App.csproj": CSPROJ})
    code, doc = fake_map(bad, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert calls_of(log) == [] and notes_of(doc)[0].startswith("global.json: not read (")


@requires_git
def test_kbingest_map_dotnet_failures_and_odd_references_are_notes(webrepo, tmp_path, monkeypatch):
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setenv("KB_FAKE_MODE", "noassets")  # no obj/project.assets.json: --no-restore cannot list packages
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0
    assert "dotnet package list (src/App): exit 1: error: No assets file was found for `App.csproj`. Please run restore." \
        in notes_of(doc)
    assert [p["name"] for p in doc["packages"]] == ["App", "Lib", "A", "B"]  # the evaluation still maps each project
    assert all("resolved" not in p for p in doc["packages"])
    monkeypatch.setenv("KB_FAKE_MODE", "outside")  # a ProjectReference that leaves the worktree
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert "src/App/App.csproj: a project reference outside the worktree, left out" in notes_of(doc)
    assert "references" not in doc["packages"][0]
    monkeypatch.setenv("KB_FAKE_MODE", "fail")  # SDK not found, or no such project
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0 and doc["packages"][0]["name"] == "App" and "framework" not in doc["packages"][0]
    assert any(n.startswith("dotnet msbuild src/App/App.csproj: exit 101") for n in notes_of(doc))


@requires_git
def test_kbingest_map_dotnet_cap_and_no_project(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setattr(kbingest, "MAP_MAX_PROJECTS", 1)
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert code == 0 and [p["name"] for p in doc["packages"]] == ["App"]
    assert "stopped after 1 projects (3 not mapped)" in notes_of(doc)
    log.unlink()
    loose = commit_files(tmp_path / "loose", {"a.cs": "class A {}\n", "global.json": "{}\n"})
    code, doc = fake_map(loose, tmp_path, monkeypatch, kbingest.DotnetMapper())
    assert notes_of(doc) == ["no .csproj, .fsproj or .vbproj file: no .NET project mapped"]
    assert seen(log, "dotnet") == [(["--version"], ".")]  # only the version


@requires_git
def test_kbingest_map_node_runs_npm_ls_with_package_lock_only_and_never_npx(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    monkeypatch.setenv("KB_TEST_API_TOKEN", "planted-token")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.NodeMapper())
    assert code == 0
    assert seen(log, "npm") == NODE_CALLS  # only where a package-lock.json sits beside package.json
    for args, _dir in seen(log, "npm")[1:]:
        assert "--package-lock-only" in args
    for c in calls_of(log):
        assert c["env"]["npm_config_offline"] == "true" and c["env"]["npm_config_ignore_scripts"] == "true"
        assert c["env"]["COREPACK_ENABLE_NETWORK"] == "0" and c["env"]["KB_TEST_API_TOKEN"] is None
    assert {c["tool"] for c in calls_of(log)} == {"npm"}  # no npx, no node, no other program
    assert doc["tools"] == {"node": {"tool": "npm", "version": "10.8.2"}}
    web = {"language": "node", "name": "web", "path": "web", "kind": "npm", "version": "1.2.0"}
    assert doc["packages"] == [{**web, "path": "."}, web]
    assert doc["imports"] == [{"language": "node", "path": "package.json", "imports": ["express", "left-pad"]},
                              {"language": "node", "path": "web/package.json", "imports": ["express", "left-pad"]}]
    assert notes_of(doc) == ["1 package.json file(s) without a package-lock.json beside them, npm ls not run"]


@requires_git
def test_kbingest_map_node_reads_the_tree_npm_prints_before_it_exits_1(webrepo, tmp_path, monkeypatch):
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setenv("KB_FAKE_MODE", "problems")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.NodeMapper())
    assert code == 0 and [p["path"] for p in doc["packages"]] == [".", "web"]
    assert "npm ls (web): 1 problem(s), first: missing: ghost@^1.0.0, required by web@1.2.0" in notes_of(doc)
    assert any(n.startswith("npm ls (web): exit 1") for n in notes_of(doc))
    monkeypatch.setenv("KB_FAKE_MODE", "fail")  # exit 101 and nothing on stdout: no tree
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.NodeMapper())
    assert code == 0 and doc["packages"] == []
    assert any(n.startswith("npm ls (.): exit 101") for n in notes_of(doc))


@requires_git
def test_kbingest_map_node_planted_missing_lock_only_and_npx_are_refused(webrepo, tmp_path, monkeypatch):
    """Planted: `npm ls` without --package-lock-only (it would read node_modules), an `npm install`, an `npx tsc` and
    an `npx npm ls`; the fake exits 64 and, for npx, logs the call, which the exact-list tests above prove absent."""
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    bad = {
        "npm ls": ["npm", "ls", "--all", "--json"],
        "npm ls --package-lock": ["npm", "ls", "--all", "--json", "--package-lock"],
        "npm install": ["npm", "install", "--package-lock-only"],
        "npx tsc": ["npx", "tsc", "--showConfig"],
        "npx npm ls": ["npx", "npm", "ls", "--all", "--json", "--package-lock-only"],
    }
    for label, args in bad.items():
        class Bad(kbingest.NodeMapper):
            def map(self, ctx, files, args=args, label=label):
                ctx.json(args, label=label)

        code, doc = fake_map(webrepo, tmp_path, monkeypatch, Bad())
        assert code == 0
        assert any(n.startswith(f"{label}: exit 64: fakelang: unexpected arguments") for n in notes_of(doc)), (label, doc["notes"])
    assert {c["tool"] for c in calls_of(log)} >= {"npx"}  # the planted calls did reach the fake npx and were logged


@requires_git
def test_kbingest_map_typescript_runs_installed_tsc_showconfig_and_listfilesonly(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0
    assert seen(log, "tsc") == TSC_CALLS  # no file on the command line: tsc reads the directory's tsconfig.json
    assert {c["tool"] for c in calls_of(log)} == {"tsc"}  # the repository's node_modules/.bin/tsc and npx never ran
    assert doc["tools"] == {"typescript": {"tool": "tsc", "version": "Version 5.6.2"}}
    root = {"language": "typescript", "name": "tsconfig.json", "path": ".", "kind": "tsconfig", "target": "es2022",
            "module": "esnext", "moduleResolution": "bundler", "strict": True,
            "files": 2}  # the lib file outside the worktree and node_modules/ are not counted
    assert doc["packages"] == [root, {**root, "name": "web/tsconfig.json", "path": "web"}]
    assert doc["imports"] == [] and doc["notes"] == []


@requires_git
def test_kbingest_map_typescript_never_uses_npx_or_the_repositorys_own_tsc(webrepo, tmp_path, monkeypatch):
    """Planted: PATH has no tsc but the worktree carries node_modules/.bin/tsc; and a mapper that goes through npx."""
    log = install_lang(tmp_path, monkeypatch, ("dotnet", "npm", "npx"))  # no tsc shim
    real = kbingest.scrub_env  # and no tsc of the host either: PATH holds the shims only
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(tmp_path / "langbin")})
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0 and doc["packages"] == [] and doc["tools"] == {}
    assert notes_of(doc) == ["toolchain not installed: tsc (4 typescript files not mapped)"]
    assert calls_of(log) == []  # not even an npx fallback

    class ViaNpx(kbingest.TypeScriptMapper):
        def project(self, ctx, cfg):
            ctx.json(["npx", "tsc", "--showConfig"], label="npx tsc --showConfig", cwd=".")

    again = tmp_path / "again"
    again.mkdir()
    install_lang(again, monkeypatch, WEB_TOOLS + ("npx",))
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(again / "langbin")})
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, ViaNpx())
    assert any(n.startswith("npx tsc --showConfig: exit 64") for n in notes_of(doc)), doc["notes"]


@requires_git
def test_kbingest_map_typescript_failures_are_notes(webrepo, tmp_path, monkeypatch):
    """Planted: a tsc that fails (an `extends` it cannot read), and a mapper that puts a file on the command line."""
    install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    monkeypatch.setenv("KB_FAKE_MODE", "fail")
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0 and doc["packages"] == []
    assert any(n.startswith("tsc --showConfig (web): exit 101") for n in notes_of(doc))
    assert any(n.startswith("tsc --listFilesOnly (.): exit 101") for n in notes_of(doc))
    monkeypatch.delenv("KB_FAKE_MODE")

    class WithFile(kbingest.TypeScriptMapper):
        def project(self, ctx, cfg):
            ctx.json(["tsc", "--showConfig", "src/a.ts"], label="tsc with a file", cwd=".")

    code, doc = fake_map(webrepo, tmp_path, monkeypatch, WithFile())
    assert any(n.startswith("tsc with a file: exit 64") for n in notes_of(doc)), doc["notes"]
    loose = commit_files(tmp_path / "loose", {"a.ts": "export {};\n"})
    code, doc = fake_map(loose, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert notes_of(doc) == ["no tsconfig.json: no TypeScript project mapped"]


@requires_git
def test_kbingest_map_dotnet_node_typescript_are_registered_and_selected_by_lang(webrepo, tmp_path, monkeypatch):
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS + ("npx",))
    out = tmp_path / "web.json"
    assert kbingest.main(["map", webrepo.path, "--out", str(out), "--lang", "dotnet,node,typescript"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert sorted(doc["tools"]) == ["dotnet", "node", "typescript"]
    assert [(c["tool"], c["args"], where(c)) for c in calls_of(log)] == \
        [("dotnet", a, d) for a, d in DOTNET_CALLS] + [("npm", a, d) for a, d in NODE_CALLS] + \
        [("tsc", a, d) for a, d in TSC_CALLS]
    log.unlink()
    assert kbingest.main(["map", webrepo.path, "--out", str(out), "--lang", "typescript"]) == 0
    assert {c["tool"] for c in calls_of(log)} == {"tsc"}  # --lang typescript never starts npm or dotnet


@requires_git
def test_kbingest_map_missing_dotnet_npm_and_tsc_are_notes(webrepo, tmp_path, monkeypatch):
    """Planted: a PATH with none of the three programs (nothing is installed for the operator)."""
    empty = tmp_path / "empty"
    empty.mkdir()
    real = kbingest.scrub_env
    monkeypatch.setattr(kbingest, "scrub_env", lambda base=None: {**real(base), "PATH": str(empty)})
    out = tmp_path / "none.json"
    assert kbingest.main(["map", webrepo.path, "--out", str(out), "--lang", "dotnet,node,typescript"]) == 0
    doc = json.loads(out.read_text(encoding="utf-8"))
    assert doc["tools"] == {} and doc["packages"] == []
    assert notes_of(doc) == ["toolchain not installed: dotnet (8 dotnet files not mapped)",
                             "toolchain not installed: npm (3 node files not mapped)",
                             "toolchain not installed: tsc (4 typescript files not mapped)"]


@requires_git
def test_kbingest_map_a_program_inside_the_worktree_is_never_run(webrepo, tmp_path, monkeypatch):
    """Planted: PATH resolves `tsc` to a file under the worktree (as a relative or repository entry would)."""
    log = install_lang(tmp_path, monkeypatch, WEB_TOOLS)
    real = kbingest.tool_exe
    monkeypatch.setattr(kbingest, "tool_exe", lambda tool, env, root: (real(tool, env, root)[0], True))
    code, doc = fake_map(webrepo, tmp_path, monkeypatch, kbingest.TypeScriptMapper())
    assert code == 0 and doc["tools"] == {} and doc["packages"] == []
    assert notes_of(doc) == ["tsc: found inside the worktree, the repository's own program is never run "
                             "(4 typescript files not mapped)"]
    assert calls_of(log) == []


def test_kbingest_map_tool_exe_tells_the_repositorys_program_from_the_installed_one(tmp_path):
    root, outside = tmp_path / "tree", tmp_path / "usr"
    (root / "node_modules" / ".bin").mkdir(parents=True)
    outside.mkdir()
    name = "tsc.cmd" if os.name == "nt" else "tsc"
    for folder in (root / "node_modules" / ".bin", outside):
        (folder / name).write_text("x\n", encoding="utf-8", newline="\n")
        (folder / name).chmod(0o755)
    exe, inside = kbingest.tool_exe("tsc", {"PATH": str(outside)}, root)
    assert exe is not None and inside is False
    exe, inside = kbingest.tool_exe("tsc", {"PATH": str(root / "node_modules" / ".bin")}, root)
    assert exe is not None and inside is True  # planted: the repository's node_modules/.bin on PATH
    assert kbingest.tool_exe("tsc", {"PATH": str(tmp_path / "nowhere")}, root) == (None, False)


@pytest.mark.skipif(os.name == "nt", reason="a relative PATH entry resolves differently on Windows")
def test_kbingest_map_relative_path_entry_is_resolved_against_the_caller_not_the_worktree(tmp_path, monkeypatch):
    """Planted: PATH=bin, and both the caller's directory and the worktree hold bin/probe; only the caller's may run."""
    caller, tree = tmp_path / "caller", tmp_path / "tree"
    for base, text in ((caller, "caller"), (tree, "worktree")):
        (base / "bin").mkdir(parents=True)
        probe = base / "bin" / "probe"
        probe.write_text(f"#!/bin/sh\necho {text}\n", encoding="utf-8", newline="\n")
        probe.chmod(0o755)
    monkeypatch.chdir(caller)
    r = kbingest.run_tool(["probe"], tree, {"PATH": "bin"}, 30)
    assert r.rc == 0 and r.out.strip() == b"caller"


# ---- pins ----------------------------------------------------------------------------------------------------------

PIN_FILES = {
    ".python-version": "3.12\n# a comment\n",
    "pyproject.toml": "[project]\nname = 'svc'\nrequires-python = \">=3.10\"\n",
    "uv.lock": "version = 1\nrevision = 3\nrequires-python = \">=3.10\"\n",
    "vendor/uv.lock": "version = 1\nrequires-python = \">=2.7\"\n",
    "vendor/package.json": '{"engines": {"node": ">=4"}}\n',
    "web/package.json": json.dumps({"name": "web", "engines": {"node": ">=20", "npm": "^10"},
                                    "devEngines": {"runtime": {"name": "node", "version": "^20", "onFail": "error"},
                                                   "packageManager": [{"name": "pnpm", "version": "9"}]},
                                    "packageManager": "pnpm@9.1.0"}),
    "web/.nvmrc": "v20.11.0\n",
    "web/tsconfig.json": '{ // the base\n  "extends": ["@tsconfig/node20/tsconfig.json", "./base.json"], /* c */\n'
                         '  "note": "a // b /* c */",\n  "compilerOptions": {"paths": {"@a/*": ["src/*",],},},\n}\n',
    "go/go.mod": "module example.com/x\n\ngo 1.22.0\n\ntoolchain go1.22.3 // suggested\n\n"
                 "require (\n\tgolang.org/x/text v0.14.0\n)\n",
    "go/go.work": "go 1.23\n\nuse (\n\t./a // first\n\t./b\n)\nuse ./c\n",
    "rs/rust-toolchain.toml": '[toolchain]\nchannel = "1.78.0"\ncomponents = ["clippy"]\n',
    "rs/legacy/rust-toolchain": "nightly-2024-05-01\n",
    "rs/Cargo.toml": '[package]\nname = "x"\nedition = "2021"\nrust-version = "1.70"\n',
    "rs/ws/Cargo.toml": '[workspace]\nmembers = []\n\n[workspace.package]\nedition = "2024"\nrust-version = "1.85"\n',
    "rs/member/Cargo.toml": '[package]\nname = "m"\nedition.workspace = true\nrust-version.workspace = true\n',
    "java/pom.xml": '<?xml version="1.0"?>\n<project xmlns="http://maven.apache.org/POM/4.0.0"><properties>'
                    '<maven.compiler.release>17</maven.compiler.release></properties><build><plugins><plugin>'
                    '<configuration><release>21</release></configuration></plugin></plugins></build></project>\n',
    "java/gradle/wrapper/gradle-wrapper.properties":
        "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.7-bin.zip\ndistributionSha256Sum=abc123\n",
    "java/build.gradle.kts": "java { toolchain { languageVersion.set(JavaLanguageVersion.of(21)) } }\n",
    "dn/global.json": '{\n  // pinned by the team\n  "sdk": {"version": "8.0.100", /* roll */ "rollForward": "latestFeature",},\n}\n',
    "dn/src/App/App.csproj": '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFrameworks>net8.0;net9.0</TargetFrameworks>'
                             '<LangVersion>12.0</LangVersion></PropertyGroup></Project>\n',
    "dn/Directory.Packages.props": '<Project><PropertyGroup><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>'
                                   '</PropertyGroup><ItemGroup><PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />'
                                   '</ItemGroup></Project>\n',
    "dn/src/App/packages.lock.json": json.dumps({"version": 1, "dependencies": {"net8.0": {
        "Newtonsoft.Json": {"type": "Direct", "requested": "[13.0.3, )", "resolved": "13.0.3"},
        "System.Memory": {"type": "Transitive", "resolved": "4.5.5"}}}}),
    "ps/run.ps1": "#Requires -Version 5.1 # for the parser\nparam()\n#requires -Modules Az.Accounts\n",
    "ps/Mod/Mod.psd1": "@{\n  # PowerShellVersion = '2.0'\n  PowerShellVersion = '5.1'\n  CompatiblePSEditions = @('Desktop', 'Core')\n"
                       "  RequiredModules = @(\n    'Az.Accounts', # first\n    @{ ModuleName = 'Pester'; ModuleVersion = '5.5.0' },\n"
                       "    \"$(Get-Date)\"\n  )\n  FunctionsToExport = $(Invoke-Expression 'boom')\n}\n",
    "env/.devcontainer/devcontainer.json":
        '{ // the image\n  "image": "mcr.microsoft.com/devcontainers/python:3.12",\n  "features": {\n'
        '    "ghcr.io/devcontainers/features/node:1": {"version": "20"},\n    "ghcr.io/devcontainers/features/go:1": {},\n'
        '    "ghcr.io/example/feat/tool:2": {"token": "not-a-real-value"},\n  },\n}\n',
    "env/.devcontainer/devcontainer-lock.json": json.dumps({"features": {"ghcr.io/devcontainers/features/node:1": {
        "version": "1.5.0", "resolved": "ghcr.io/devcontainers/features/node@sha256:0abc", "integrity": "sha256:0abc"}}}),
    "env/.tool-versions": "nodejs 20.11.0 18.19.0 # two\npython 3.12.1\n",
    "env/mise.toml": '[tools]\nnode = "20"\npython = ["3.12", "3.11"]\ngo = { version = "1.22", postinstall = "x" }\n',
}


def survey_pins(repo, max_bytes=1_000_000):
    """(rows, notes) of the pins the way `survey --pins` finds them: the survey's tree, attributes and rules."""
    commit = kbingest.resolve(repo.path, "HEAD")
    entries = kbingest.tree(repo.path, commit)
    attrs, _where = kbingest.attributes(repo.path, commit, [p for p, k, _, _ in entries if k == "blob"])
    rows = kbingest.classify(entries, attrs, max_bytes, lambda oids: kbingest.contents(repo.path, oids))
    return kbingest.pins(entries, rows, lambda oids: kbingest.contents(repo.path, oids), max_bytes)


def pin_of(rows, path):
    return [(pin, value) for f, pin, value in rows if f == path]


@pytest.fixture(scope="module")
def pinrepo(tmp_path_factory):
    r = commit_files(tmp_path_factory.mktemp("pins") / "stack", PIN_FILES)
    r.write(".python-version", "2.7\n")  # uncommitted: the pins are read at the commit
    return r


@requires_git
def test_kbingest_pin_files_python_and_node(pinrepo):
    rows, notes = survey_pins(pinrepo)
    assert notes == []
    assert pin_of(rows, ".python-version") == [("python-version", "3.12")]
    assert pin_of(rows, "pyproject.toml") == [("requires-python", ">=3.10")]
    assert ("uv.lock requires-python", ">=3.10") in pin_of(rows, "uv.lock")  # the survey leaves uv.lock out as generated
    assert pin_of(rows, "vendor/uv.lock") == [] and pin_of(rows, "vendor/package.json") == []
    assert pin_of(rows, "web/package.json") == [
        ("engines.node", ">=20"), ("engines.npm", "^10"), ("devEngines.runtime", "node ^20 (onFail error)"),
        ("devEngines.packageManager", "pnpm 9"), ("packageManager", "pnpm@9.1.0")]
    assert pin_of(rows, "web/.nvmrc") == [(".nvmrc", "v20.11.0")]
    assert pin_of(rows, "web/tsconfig.json") == [("extends", "@tsconfig/node20/tsconfig.json"), ("extends", "./base.json")]


@requires_git
def test_kbingest_pin_files_go_rust_and_java(pinrepo):
    rows, _notes = survey_pins(pinrepo)
    assert pin_of(rows, "go/go.mod") == [("go", "1.22.0"), ("toolchain", "go1.22.3")]
    assert pin_of(rows, "go/go.work") == [("go", "1.23"), ("use", "./a"), ("use", "./b"), ("use", "./c")]
    assert pin_of(rows, "rs/rust-toolchain.toml") == [("channel", "1.78.0")]
    assert pin_of(rows, "rs/legacy/rust-toolchain") == [("channel", "nightly-2024-05-01")]
    assert pin_of(rows, "rs/Cargo.toml") == [("rust-version", "1.70"), ("edition", "2021")]
    assert pin_of(rows, "rs/ws/Cargo.toml") == [("workspace.rust-version", "1.85"), ("workspace.edition", "2024")]
    assert pin_of(rows, "rs/member/Cargo.toml") == [("rust-version", "workspace=true"), ("edition", "workspace=true")]
    assert pin_of(rows, "java/pom.xml") == [("maven.compiler.release", "17"), ("release", "21")]
    assert pin_of(rows, "java/gradle/wrapper/gradle-wrapper.properties") == [
        ("distributionUrl", "https://services.gradle.org/distributions/gradle-8.7-bin.zip"),
        ("distributionSha256Sum", "abc123")]
    assert pin_of(rows, "java/build.gradle.kts") == [("java.toolchain.languageVersion", "21")]


@requires_git
def test_kbingest_pin_files_dotnet(pinrepo):
    rows, _notes = survey_pins(pinrepo)
    assert pin_of(rows, "dn/global.json") == [("sdk.version", "8.0.100"), ("sdk.rollForward", "latestFeature")]
    assert pin_of(rows, "dn/src/App/App.csproj") == [("TargetFrameworks", "net8.0;net9.0"), ("LangVersion", "12.0")]
    assert pin_of(rows, "dn/Directory.Packages.props") == [
        ("ManagePackageVersionsCentrally", "true"), ("PackageVersion Newtonsoft.Json", "13.0.3")]
    # packages.lock.json is left out by the survey as generated, and still a pin file: direct packages only
    assert pin_of(rows, "dn/src/App/packages.lock.json") == [
        ("packages.lock.json version", "1"), ("locked net8.0/Newtonsoft.Json", "13.0.3")]


@requires_git
def test_kbingest_pin_files_powershell_is_read_as_text_never_evaluated(pinrepo):
    rows, notes = survey_pins(pinrepo)
    assert notes == []
    assert pin_of(rows, "ps/run.ps1") == [("#Requires", "-Version 5.1"), ("#Requires", "-Modules Az.Accounts")]
    psd1 = dict(pin_of(rows, "ps/Mod/Mod.psd1"))
    assert psd1["PowerShellVersion"] == "'5.1'"  # the commented '2.0' line is not read
    assert psd1["CompatiblePSEditions"] == "@('Desktop', 'Core')"
    assert psd1["RequiredModules"].startswith("@( 'Az.Accounts',") and "ModuleVersion = '5.5.0'" in psd1["RequiredModules"]
    assert '"$(Get-Date)"' in psd1["RequiredModules"]  # the subexpression stays text
    assert "FunctionsToExport" not in psd1 and "boom" not in str(rows)


@requires_git
def test_kbingest_pin_files_environment(pinrepo):
    rows, _notes = survey_pins(pinrepo)
    dev = pin_of(rows, "env/.devcontainer/devcontainer.json")
    assert dev == [("image", "mcr.microsoft.com/devcontainers/python:3.12"),
                   ("feature ghcr.io/devcontainers/features/node:1", "20"),
                   ("feature ghcr.io/devcontainers/features/go:1", ""),
                   ("feature ghcr.io/example/feat/tool:2", "options: token")]  # an option's value is never copied
    assert "not-a-real-value" not in str(rows)
    assert pin_of(rows, "env/.devcontainer/devcontainer-lock.json") == [
        ("locked feature ghcr.io/devcontainers/features/node:1", "1.5.0 ghcr.io/devcontainers/features/node@sha256:0abc")]
    assert pin_of(rows, "env/.tool-versions") == [("nodejs", "20.11.0 18.19.0"), ("python", "3.12.1")]
    assert pin_of(rows, "env/mise.toml") == [("tools.node", "20"), ("tools.python", "3.12, 3.11"), ("tools.go", "1.22")]


MALFORMED = {
    "good/.python-version": "3.13\n",
    "json/package.json": '{"engines": ', "json/tsconfig.json": "{ /* never closed", "json/global.json": '{"sdk": {"version": "8",,}}',
    "json/packages.lock.json": "{", "json/devcontainer.json": '{"image":', "json/devcontainer-lock.json": "[1,",
    "toml/pyproject.toml": '[project\nrequires-python = ">=3"\n', "toml/Cargo.toml": "= =\n", "toml/uv.lock": "= broken\n",
    "toml/rust-toolchain.toml": "[toolchain\n", "toml/mise.toml": "[tools\nnode =\n",
    "xml/pom.xml": "<project><properties>", "xml/App.csproj": "<Project><PropertyGroup>", "xml/Directory.Packages.props": "not xml\n",
    "text/Mod.psd1": "@{ RequiredModules = @( 'a'\n", "text/quote.psd1": "@{ PowerShellVersion = '5.1\n}\n",
    "text/go.mod": "go\n", "text/go.work": "use (\n\t./a\n", "text/gradle-wrapper.properties": "distributionUrl=\n",
    "text/.tool-versions": "nodejs\n", "text/.nvmrc": " \n", "text/.python-version": "# nothing\n",
    "text/run.ps1": "#Requires\n",
}


@requires_git
def test_kbingest_pin_files_one_malformed_file_per_format_is_a_note_not_a_crash(tmp_path):
    r = commit_files(tmp_path / "bad", MALFORMED)
    rows, notes = survey_pins(r)
    bad = {p for p in MALFORMED if p.split("/")[0] != "good"}
    assert {path for path, _ in notes} == bad, notes
    assert all(message for _, message in notes)
    assert rows == [("good/.python-version", "python-version", "3.13")], "the malformed files add no rows"


@requires_git
def test_kbingest_pin_files_a_reader_that_crashes_is_a_note(tmp_path, monkeypatch):
    r = commit_files(tmp_path / "crash", {".python-version": "3.13\n", "go.mod": "go 1.22\n"})

    def boom(text, out):
        raise RuntimeError("planted")
    monkeypatch.setattr(kbingest, "PIN_READERS", [(rx, boom if "go" in rx.pattern else f, b) for rx, f, b in kbingest.PIN_READERS])
    rows, notes = survey_pins(r)
    assert rows == [(".python-version", "python-version", "3.13")]
    assert notes == [("go.mod", "not read: RuntimeError: planted")]


@requires_git
def test_kbingest_pin_files_only_kept_files_and_generated_locks_are_read(tmp_path):
    r = commit_files(tmp_path / "scope", {
        ".python-version": "3.13\n", "big/.python-version": "3.11\n" + "# pad\n" * 400, "pyproject.toml": "[project]\n",
        "uv.lock": 'requires-python = ">=3.13"\n' + "# pad\n" * 400, ".gitattributes": "attr/.nvmrc linguist-vendored\n",
        "attr/.nvmrc": "v18\n", "node_modules/pkg/.nvmrc": "v16\n"})
    rows, notes = survey_pins(r, max_bytes=4000)
    assert notes == []
    assert {f for f, _, _ in rows} == {".python-version", "big/.python-version", "uv.lock"}, rows
    rows, _ = survey_pins(r, max_bytes=100)
    assert [f for f, _, _ in rows] == [".python-version"], "a file over --max-bytes, a lock file included, is not read"


def test_kbingest_pin_files_row_cap_is_a_note():
    rows, notes = [], []
    out = kbingest.PinOut("Directory.Packages.props", rows, notes)
    for i in range(kbingest.PIN_MAX_ROWS + 30):
        out.add(f"PackageVersion P{i}", "1.0")
    assert len(rows) == kbingest.PIN_MAX_ROWS and len(notes) == 1


def test_kbingest_pin_files_jsonc_scanner():
    assert kbingest.jsonc('{"a": "x // y", /* c */ "b": [1, 2,], // tail\n}') == {"a": "x // y", "b": [1, 2]}
    assert kbingest.jsonc('﻿{"a": "q\\"/*not*/"}') == {"a": 'q"/*not*/'}
    for bad in ('{"a": 1 /* open', '{"a": 1,,}', '{"a": "open'):
        with pytest.raises(ValueError):
            kbingest.jsonc(bad)


@requires_git
def test_kbingest_pin_files_survey_prints_the_pins(pinrepo):
    code, out = run("survey", pinrepo.path, "--pins")
    assert code == 0, out
    lines = [ln.split("\t") for ln in out.splitlines() if ln.startswith("pin\t")]
    assert ["pin", "pyproject.toml", "requires-python", ">=3.10"] in lines
    assert ["pin", ".python-version", "python-version", "3.12"] in lines  # the commit's, not the working tree's 2.7
    assert ["pin", "dn/global.json", "sdk.version", "8.0.100"] in lines
    assert "pins: " in out and "codebase-mapping.csv" in out
    assert not any(ln.startswith("pin\t") for ln in run("survey", pinrepo.path)[1].splitlines()), "--pins is opt-in"


@requires_git
def test_kbingest_pin_files_survey_prints_notes_for_malformed_files(tmp_path):
    r = commit_files(tmp_path / "bad", {"package.json": "{", ".python-version": "3.13\n"})
    code, out = run("survey", r.path, "--pins")
    assert code == 0, out
    assert "note: pins: package.json: not read: JSONDecodeError" in out and "pin\t.python-version\tpython-version\t3.13" in out


# ---- drift -------------------------------------------------------------------------------------------------------

TOOL_V1 = ("def keep(x):\n    return x\n\n\ndef change(x):\n    return x + 1\n\n\ndef gone(x):\n    return x\n\n\n"
           "def vanish():\n    return 0\n\n\nclass Widget:\n    def method(self):\n        return 1\n")
TOOL_V2 = ("# a new header comment\n# and another\n\ndef keep(x):\n    return x\n\n\ndef change(x):\n    return x + 2\n\n\n"
           "def gone2(x):\n    return x\n\n\nprint(gone(1))\n\n\nclass Widget:\n    def method(self):\n        return 1\n\n"
           "    def extra(self):\n        return 2\n")
DRIFT_HOST, DRIFT_PROJECT = "gitlab.corp.example.com", "ops/deploy"
# (key, file, anchor): the CODE facts of the fixture root, each citing its file at the first commit
DRIFT_FACTS = (
    ("keep", "app/tool.py", "keep"), ("change", "app/tool.py", "change"), ("gone", "app/tool.py", "gone"),
    ("vanish", "app/tool.py", "vanish"), ("method", "app/tool.py", "Widget.method"),
    ("moved", "lib/moved.go", "Moved"), ("removed", "lib/removed.ps1", "Remove-Me"),
    ("limit", "conf/settings.yaml", "limit"), ("name", "conf/settings.yaml", "name"),
    ("range-moved", "notes.txt", "L2-L3"), ("range-changed", "notes.txt", "L5"), ("range-same", "notes.txt", "L1-L1"),
)


class Drift:
    """A repository with two commits and a kb root whose CODE facts cite the first."""

    def __init__(self, base):
        self.repo = commit_files(base / "deploy", {
            "app/tool.py": TOOL_V1, "lib/moved.go": "func Moved() int {\n\treturn 1\n}\n",
            "lib/removed.ps1": "function Remove-Me {\n  1\n}\n", "conf/settings.yaml": "limit: 5\nname: x\n",
            "notes.txt": "alpha\nbeta\ngamma\ndelta\nepsilon\nzeta\n"})
        self.repo.git("remote", "add", "origin", f"https://jan.kowalski:tok@{DRIFT_HOST}/{DRIFT_PROJECT}.git")
        self.old = self.repo.rev("HEAD")
        self.repo.write("app/tool.py", TOOL_V2)
        self.repo.write("conf/settings.yaml", "limit: 10\nname: x\n")
        self.repo.write("notes.txt", "alpha\nnew\nbeta\ngamma\ndelta\nEPSILON\nzeta\n")
        self.repo.git("mv", "lib/moved.go", "lib/moved_here.go")
        self.repo.git("rm", "-q", "lib/removed.ps1")
        self.repo.git("add", "-A")
        self.repo.git("commit", "-q", "-m", "second")
        self.new = self.repo.rev("HEAD")
        self.root = base / "codefix"
        self.write_root()

    def url(self, rel, commit=None, project=DRIFT_PROJECT):
        return kbingest.pin_url("gitlab", DRIFT_HOST, project, commit or self.old, rel)

    def write_root(self):
        root = self.root
        (root / "code").mkdir(parents=True)
        (root / "_root.md").write_text("---\nroot: codefix\nid_prefix: FXT\nvisibility: internal\n"
                                       "description: drift fixture\n---\n", encoding="utf-8", newline="\n")
        urls = {rel: self.url(rel) for _, rel, _ in DRIFT_FACTS}
        urls["other.go"] = self.url("other.go", project="ops/other")
        urls["unknown.go"] = self.url("unknown.go", commit="ab" * 20)
        sids = {rel: kbid.source_id(u, "FXT") for rel, u in urls.items()}
        rows = ["id,url,title,publisher,licence,reuse,retrieved_utc,version_or_date,artifact_sha256,used_in,superseded_by"]
        rows += [f"{sids[rel]},{u},{rel},corp.example.com,internal,quote,2026-09-26,,,code/tool.md," for rel, u in urls.items()]
        (root / "_sources.csv").write_text("\n".join(rows) + "\n", encoding="utf-8", newline="\n")
        lines = ["---", "topic: code/tool", "priority: P1", "retrieved_utc: 2026-09-26", "status: partial", "---", "",
                 "# Tool", "", "## Facts"]
        self.at = {}
        for key, rel, anchor in DRIFT_FACTS + (("other", "other.go", "Run"), ("unknown", "unknown.go", "Run")):
            self.at[key] = len(lines) + 1
            lines.append(f"- The fact {key} reads {anchor}. [CODE {sids[rel]}: {rel}#{anchor}]")
        lines.append(f"- A documented fact stays out. [DOC {sids['app/tool.py']}]")
        (root / "code" / "tool.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    def run(self, *args, repo=None):
        return run("drift", str(repo or self.repo.path), *args, env=git_env(KB_ROOTS=str(self.root)))

    def findings(self, out):
        """{kb line: (kind, path#symbol, detail)} of the finding lines."""
        got = {}
        for ln in out.splitlines():
            if ln.startswith("finding\t"):
                _, kind, where, _sid, label, detail = ln.split("\t")
                got[int(where.rsplit(":", 1)[1])] = (kind, label, detail)
        return got


@pytest.fixture(scope="module")
def drift(tmp_path_factory):
    return Drift(tmp_path_factory.mktemp("drift"))


@requires_git
def test_kbingest_drift_reports_each_kind_of_moved_evidence(drift):
    code, out = drift.run("--root", "codefix")
    assert code == 1, out
    got = drift.findings(out)
    kinds = {key: got[line][0] for key, line in drift.at.items() if line in got}
    assert kinds == {"change": "changed", "gone": "symbol-missing", "vanish": "symbol-missing", "moved": "moved",
                     "removed": "file-missing", "limit": "changed", "range-moved": "moved",
                     "range-changed": "changed", "unknown": "unverifiable"}, out
    assert "still mentioned on 1 lines" in got[drift.at["gone"]][2]
    assert "does not occur" in got[drift.at["vanish"]][2]
    assert "lib/moved_here.go" in got[drift.at["moved"]][2] and "unchanged" in got[drift.at["moved"]][2]
    assert got[drift.at["range-moved"]][2] == "lines 2-3 are now lines 3-4"
    assert got[drift.at["change"]][1] == "app/tool.py#change"
    assert f"finding\tchanged\tcodefix/code/tool.md:{drift.at['limit']}\t" in out, "the kb path is qualified"
    assert f"commit: {drift.new} (HEAD)" in out


@requires_git
def test_kbingest_drift_unchanged_evidence_is_not_reported(drift):
    code, out = drift.run("--root", "codefix")
    got = drift.findings(out)
    for key in ("keep", "method", "name", "range-same", "other"):
        assert drift.at[key] not in got, (key, out)  # the file moved lines, changed elsewhere, or is another repository's
    assert out.splitlines()[-1] == "checked=13 unchanged=4 findings=9 elsewhere=1", out
    # planted: at the commit the facts cite, nothing differs; only the fact whose commit is not in the clone remains
    code, out = drift.run("--root", "codefix", "--rev", drift.old)
    assert code == 1 and set(drift.findings(out)) == {drift.at["unknown"]}, out
    assert out.splitlines()[-1] == "checked=13 unchanged=12 findings=1 elsewhere=1", out


@requires_git
def test_kbingest_drift_prefix_and_root_narrow_the_facts(drift):
    code, out = drift.run("--root", "codefix", "--prefix", "codefix/code/tool")
    assert code == 1 and "checked=13" in out, out
    code, out = drift.run("--root", "codefix", "--prefix", "codefix/nowhere")
    assert code == 0 and "checked=0" in out, out
    code, out = drift.run("--root", "public")
    assert "codefix" not in out and "checked=0" in out, out


def tree_files(path):
    return {p: p.read_bytes() for p in Path(path).rglob("*") if p.is_file() and ".git" not in p.parts}


@requires_git
def test_kbingest_drift_writes_nothing(drift):
    root, repo = tree_files(drift.root), tree_files(drift.repo.path)
    status = drift.repo.git("status", "--porcelain")
    assert drift.run("--root", "codefix")[0] == 1
    assert tree_files(drift.root) == root and tree_files(drift.repo.path) == repo
    assert drift.repo.git("status", "--porcelain") == status


@requires_git
def test_kbingest_drift_refusals(drift, tmp_path):
    code, out = drift.run("--rev", "no-such-rev")
    assert code == 2 and "refused" in out, out
    code, out = drift.run("--root", "nosuchroot")
    assert code == 2 and "no root 'nosuchroot'" in out, out
    bare = commit_files(tmp_path / "bare", {"a.txt": "x\n"})  # no remote: nothing to match the source rows to
    code, out = drift.run(repo=bare.path)
    assert code == 2 and "--remote" in out, out
    # with --remote the rows match, but this clone lacks the commits they cite: unverifiable, not silent
    code, out = drift.run("--root", "codefix", "--remote", f"{DRIFT_HOST}/{DRIFT_PROJECT}", repo=bare.path)
    assert code == 1 and out.count("finding\tunverifiable\t") == 13, out
    code, out = run("drift", str(tmp_path / "missing"))
    assert code == 2 and "refused" in out, out


@requires_git
def test_kbingest_drift_a_rename_with_a_changed_symbol_says_both(tmp_path):
    d = Drift(tmp_path)
    d.repo.write("lib/moved_here.go", "func Moved() int {\n\treturn 2\n}\n")
    d.repo.git("add", "-A")
    d.repo.git("commit", "-q", "-m", "third")
    code, out = d.run("--root", "codefix")
    kind, _label, detail = d.findings(out)[d.at["moved"]]
    assert kind == "moved" and "lib/moved_here.go; changed: the definition of Moved differs" in detail, out


def test_kbingest_drift_pin_parts_read_the_forge_url_forms():
    sha = "ab" * 20
    assert kbingest.pin_parts(f"https://raw.githubusercontent.com/o/r/{sha}/src/a%20b.rs") == ("github.com", "o/r", sha, "src/a b.rs")
    assert kbingest.pin_parts(f"https://github.com/o/r/blob/{sha}/x.go#L4") == ("github.com", "o/r", sha, "x.go")
    assert kbingest.pin_parts(f"https://{DRIFT_HOST}/ops/deploy/-/raw/{sha}/a/b.go") == (DRIFT_HOST, "ops/deploy", sha, "a/b.go")
    assert kbingest.pin_parts("https://gitlab.com/g/sub/p/-/blob/refs/tags/v1/a.go") == ("gitlab.com", "g/sub/p", "refs/tags/v1", "a.go")
    for other in ("https://learn.microsoft.com/en-us/x", "https://raw.githubusercontent.com/o/r/-x/a.go", ""):
        assert kbingest.pin_parts(other) is None


def test_kbingest_drift_definitions_are_not_calls():
    defs = {
        "python": ("def name(x):", "async def name():", "class name:"),
        "go": ("func name() int {", "func (r T) name(x int) {", "type name struct {"),
        "rust": ("pub fn name() {", "pub(crate) struct name {", "impl name {"),
        "js": ("export function name() {", "name(a) {", "const name = () => 1;"),
        "csharp": ("    public static int name(string s)", "    internal class name"),
        "powershell": ("function name {",),
        "config": ("name: 1", '"name": 2', "name = 3", "  name:"),
    }
    for lang, lines in defs.items():
        for ln in lines:
            assert kbingest.definition_lines([ln], "name") == [0], (lang, ln)
    calls = ("    x = name(1)", "return name(2)", "name(3);", "await name()", "if name(x):", "print(name(1))", "# def other",
             "name == 4", "renamed = 1", "my-name: 2", "name_two(x) {")
    for ln in calls:
        assert kbingest.definition_lines([ln], "name") == [], ln
    assert kbingest.symbol_of("Widget.method") == "method" and kbingest.symbol_of("mod::func") == "func"
    assert kbingest.symbol_of("L10-L20") is None


def test_kbingest_drift_a_definition_is_its_body():
    old = ["def f(x):", "    return 1", "", "def g():", "    pass"]
    assert kbingest.span_of(old, 0) == "def f(x):\n    return 1"
    assert kbingest.span_of(["func F() {", "\treturn 1", "}", "func G() {}"], 0) == "func F() {\n\treturn 1\n}"
    assert kbingest.compare_evidence(old, old + ["x = 1"], "f") is None
    assert kbingest.compare_evidence(old, ["def f(x):", "    return 2"], "f")[0] == "changed"
    assert kbingest.compare_evidence(old, ["def g():", "    pass"], "f") == ("symbol-missing", "f does not occur")
