"""kbingest.py: the survey of a repository before /kb-ingest turns it into facts of a root.

A throwaway repository with planted files: secret files, vendored and generated code (by path, by .gitattributes,
by header), a binary and an oversized file are left out; an unset attribute keeps a file; a secret shape in a kept
file is flagged; an uncommitted change is not read; the pinned urls pass the CODE lint's pinned-source rule; remote
urls lose their credentials; the refusals exit 2.
"""
import subprocess, sys
from pathlib import Path

import pytest

from conftest import Repo, TOOLS, git_env, requires_git

import kbfacts, kbingest

TOOL = str(Path(TOOLS) / "kbingest.py")
SECRET_LINE = "pass" + "word: '" + "x" * 12 + "'\n"  # built here so the leak scan of this file stays clean
GO_GEN = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"


def run(*args, cwd=None):
    p = subprocess.run([sys.executable, TOOL, *args], capture_output=True, text=True, encoding="utf-8",
                       errors="replace", env=git_env(), cwd=cwd, timeout=60)
    return p.returncode, p.stdout + p.stderr


@pytest.fixture(scope="module")
def repo(tmp_path_factory):
    r = Repo(tmp_path_factory.mktemp("ingest") / "deploy")
    Path(r.path).mkdir()
    r.git("init", "-q", "-b", "main")
    files = {
        "README.md": "# deploy\n", "src/app.py": "print('hi')\n", "tests/test_app.py": "def test(): pass\n",
        ".gitlab-ci.yml": "stages: [test]\n", "config/app.yaml": "name: deploy\n" + SECRET_LINE,
        ".env": "TOKEN=x\n", ".env.example": "TOKEN=\n", "certs/server.key": "k\n",
        "vendor/lib.js": "x\n", "third_party/kept.py": "x = 1\n", "third_party/other.py": "x = 2\n",
        "package-lock.json": "{}\n", "yarn.lock": "# lock\n", "api/client.py": "x = 3\n", "api/gen.go": GO_GEN,
        "api/keep.go": GO_GEN, "big.txt": "a" * 5000 + "\n",
        ".gitattributes": "api/client.py linguist-generated\nthird_party/kept.py -linguist-vendored\n"
                          "yarn.lock -gitlab-generated\napi/keep.go -linguist-generated\n",
    }
    for rel, text in files.items():
        r.write(rel, text)
    Path(r.file("assets/logo.png")).parent.mkdir(parents=True)
    Path(r.file("assets/logo.png")).write_bytes(b"\x89PNG\0\0\0binary")
    r.git("add", "-A")
    r.git("commit", "-q", "-m", "init")
    r.git("remote", "add", "origin", "https://jan.kowalski:tok@gitlab.corp.example.com/ops/deploy.git")
    r.write("src/app.py", SECRET_LINE)  # uncommitted: the survey reads the commit, not the working tree
    return r


@requires_git
def test_survey_leaves_out_and_keeps(repo):
    code, out = run("survey", repo.path, "--files", "--max-bytes", "4000")
    assert code == 0, out
    lines = {tuple(ln.split("\t")[:3]) for ln in out.splitlines() if ln.startswith(("keep\t", "skip\t"))}
    want_skip = {(".env", "secret-file"), ("certs/server.key", "secret-file"), ("vendor/lib.js", "vendored"),
                 ("third_party/other.py", "vendored"), ("package-lock.json", "generated"), ("api/client.py", "generated"),
                 ("api/gen.go", "generated"), ("big.txt", "large"), ("assets/logo.png", "binary")}
    for path, reason in want_skip:
        assert ("skip", reason, path) in lines, (path, out)
    want_keep = {("README.md", "doc"), ("src/app.py", "code"), ("tests/test_app.py", "test"), (".gitlab-ci.yml", "ci"),
                 ("config/app.yaml", "config"), (".env.example", "config"), ("third_party/kept.py", "code"),
                 ("yarn.lock", "other"), ("api/keep.go", "code")}
    for path, kind in want_keep:
        assert ("keep", kind, path) in lines, (path, out)
    secret = [ln for ln in out.splitlines() if ln.startswith("keep\t") and ln.endswith("\tsecret")]
    assert [ln.split("\t")[2] for ln in secret] == ["config/app.yaml"], out  # src/app.py's change is uncommitted
    assert "tok" not in out and "jan.kowalski" not in out, "credentials in the remote url must never be printed"
    assert "remote: origin gitlab.corp.example.com/ops/deploy (forge gitlab)" in out
    assert "on a remote branch: no" in out and "worktree: differs from the commit" in out


@requires_git
def test_pinned_urls_pass_the_code_lint(repo):
    code, url = run("url", repo.path, "src/app.py")
    commit = repo.rev("HEAD")
    assert code == 0 and url.strip() == f"https://gitlab.corp.example.com/ops/deploy/-/raw/{commit}/src/app.py", url
    assert kbfacts.pinned_source({"url": url.strip()})
    assert run("url", repo.path, "no/such.py")[0] == 2


@requires_git
def test_refusals(repo, tmp_path):
    assert run("survey", str(tmp_path))[0] == 2  # not a repository
    assert run("survey", repo.path, "--rev", "no-such-rev")[0] == 2
    bare = Repo(tmp_path / "local")
    Path(bare.path).mkdir()
    bare.git("init", "-q")
    bare.write("a.py", "x = 1\n")
    bare.git("add", "-A")
    bare.git("commit", "-q", "-m", "a")
    code, out = run("url", bare.path, "a.py")
    assert code == 2 and "no pinned url form" in out  # no remote: nothing others could open
    code, out = run("survey", bare.path)
    assert code == 0 and "remote: none" in out


def test_parse_remote_and_forge():
    cases = {
        "git@gitlab.corp.example.com:ops/deploy.git": ("gitlab.corp.example.com", "ops/deploy"),
        "ssh://git@gitlab.corp.example.com:2222/ops/sub/deploy.git": ("gitlab.corp.example.com", "ops/sub/deploy"),
        "https://jan.kowalski:tok@gitlab.corp.example.com:8443/ops/deploy": ("gitlab.corp.example.com:8443", "ops/deploy"),
        "https://github.com/o/r.git": ("github.com", "o/r"),
        "/srv/git/deploy.git": (None, None), "../deploy": (None, None), "C:\\src\\deploy": (None, None),
    }
    for url, want in cases.items():
        assert kbingest.parse_remote(url) == want, url
    assert kbingest.forge_of("github.com") == "github" and kbingest.forge_of("gitlab.com") == "gitlab"
    assert kbingest.forge_of("git.corp.example.com") is None
    assert kbingest.forge_of("git.corp.example.com", "gitlab") == "gitlab"
    assert kbingest.pin_url("github", "github.com", "o/r", "ab" * 20, "a b.py") == \
        f"https://raw.githubusercontent.com/o/r/{'ab' * 20}/a%20b.py"
    assert kbingest.pin_url("github", "ghe.corp.example.com", "o/r", "ab" * 20, "a.py") is None
