<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Identity.Client" Version="4.60.0" />
    <PackageVersion Include="Azure.Identity" Version="1.11.0" />
  </ItemGroup>
</Project>
