#!/usr/bin/env python3
"""Contract checks that _tools/check.py does not make (stdlib only). Reports only; never edits.

  lint.py                    every topic
  lint.py auth dsc/what-if   only topics whose path starts with one of these prefixes
  lint.py --json             machine output

ERROR (exit 1): topic id differs from the path; its _coverage.csv row or README coverage row is missing or out of
date (both are generated by _tools/build_index.py from the front matter, so this means "run build_index.py");
coverage lists a missing file (fix the `files:` front matter); a missing section; a DOC or COMMUNITY tag part
without a source id, a bare [DER] (tags are parsed by _tools/kbfacts.py, the grammar is in its docstring); a Facts bullet with no tag.
WARN: no H1 title; a Facts bullet mixing tag kinds; header source ids never cited in the body, or cited
ids missing from the header.
"""
import csv, glob, json, os, re, sys

KB = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, os.path.join(KB, "_tools"))
import build_index  # noqa: E402
import kbfacts  # noqa: E402
SID = re.compile(r"\bS-[a-z2-7]{8}\b|S\d+")  # hash source ids (S-k3f7q2zd) and legacy ones (S123)


def main():
    args = [a for a in sys.argv[1:] if a != "--json"]
    os.chdir(KB)
    with open("_coverage.csv", encoding="utf-8-sig", newline="") as f:
        cov = {r["topic"]: r for r in csv.DictReader(f)}
    readme = open("README.md", encoding="utf-8").read()
    try:
        gen = {r["topic"]: r for r in build_index.build()[1]}
    except build_index.BuildError as e:
        sys.exit(f"ERROR cannot build the coverage index: {e}")
    rebuild = "(run python3 _tools/build_index.py)"
    out = []

    def add(level, path, msg):
        out.append({"level": level, "path": path, "message": msg})

    for p in sorted(glob.glob("**/*.md", recursive=True)):
        if args and not any(p.startswith(a.rstrip("/")) for a in args):
            continue
        text = open(p, encoding="utf-8", errors="replace").read()
        if not text.startswith("---\n") or "\ntopic:" not in text.split("\n---", 2)[0]:
            continue
        head, body = text.split("\n---", 2)[0], text.split("\n---", 2)[-1]
        fm = dict((k.strip(), v.strip()) for k, _, v in (ln.partition(":") for ln in head.splitlines()[1:]))
        topic, want = fm.get("topic", ""), p[:-3]
        if topic != want:
            add("ERROR", p, f"topic is {topic!r}, path says {want!r}")
        row = gen.get(topic or want)
        if row:  # None: a part of another topic (named in its `files:`), e.g. an artifact digest
            if cov.get(topic) != row:
                add("ERROR", p, f"_coverage.csv row is missing or out of date {rebuild}")
            if build_index.readme_table([row]).splitlines()[-2] not in readme.splitlines():
                add("ERROR", p, f"README coverage row is missing or out of date {rebuild}")
            for f in filter(None, row["files"].split(";")):
                if not os.path.exists(f):
                    add("ERROR", p, f"_coverage.csv lists missing file {f} (fix `files:` in the front matter)")
        heads = re.findall(r"^## (.+)$", body, re.M)
        for s in ("Summary", "Facts", "Reference", "Examples"):
            if not any(h.startswith(s) for h in heads):
                add("ERROR", p, f"missing section ## {s}")
        if not re.search(r"^# ", body, re.M):
            add("WARN", p, "no '# ' title line")
        for tag in kbfacts.TAG.findall(body):
            for part in kbfacts.parse_tag(tag):
                if not part["ids"] and (part["kind"] in ("DOC", "COMMUNITY") or (part["kind"] == "DER" and not part["note"])):
                    add("ERROR", p, f"{part['kind']} tag without a source id: {' '.join(tag.split())[:70]}")
        m = re.search(r"^## Facts.*?$(.*?)(?=^## |\Z)", body, re.M | re.S)
        if m:
            for item in re.split(r"\n(?=- )", m.group(1)):
                item = item.strip()
                if not item.startswith("- "):
                    continue
                kinds = set(kbfacts.kinds_of(kbfacts.tags_in(item)))
                if not kinds:
                    add("ERROR", p, f"untagged fact: {item[2:80]!r}")
                elif len(kinds) > 1:
                    add("WARN", p, f"fact mixes tags {sorted(kinds)}: {item[2:60]!r}")
        cited = {s for tag in re.findall(r"\[(?:DOC|DER|COMMUNITY)[^\]]*\]", body) for s in SID.findall(tag)}
        fms = set(SID.findall(fm.get("sources", "")))
        if fms - cited:
            add("WARN", p, f"header sources not cited in the body: {' '.join(sorted(fms - cited))}")
        if cited - fms:
            add("WARN", p, f"cited sources missing from the header: {' '.join(sorted(cited - fms))}")

    if "--json" in sys.argv:
        print(json.dumps(out, indent=1))
    else:
        for x in out:
            print(f"{x['level']:<5} {x['path']}: {x['message']}")
        n = sum(1 for x in out if x["level"] == "ERROR")
        print(f"errors={n} warnings={len(out) - n}")
    sys.exit(1 if any(x["level"] == "ERROR" for x in out) else 0)


if __name__ == "__main__":
    main()
