#!/usr/bin/env python3
"""Contract checks that _tools/check.py does not make (stdlib only). Reports only; never edits.

  lint.py                    every topic
  lint.py auth dsc/what-if   only topics whose path starts with one of these prefixes
  lint.py --json             machine output
  lint.py --candidates [PREFIX...]   migration lists, not findings: DOC facts that cite only source-code files (CODE
                             candidates) and fenced code blocks with no SNIPPET bullet above them (SNIPPET candidates)

ERROR (exit 1): topic id differs from the path; its _coverage.csv row or _self/coverage.md row is missing or out of
date (both are generated by _tools/build_index.py from the front matter, so this means "run build_index.py");
coverage lists a missing file (fix the `files:` front matter); a missing section; a DOC, CODE or COMMUNITY tag part
without a source id, a bare [DER] (tags are parsed by _tools/kbfacts.py, the grammar is in its docstring); a Facts bullet with no tag;
a CODE part without a `path#symbol` pointer or citing a source that is not pinned to a tag or commit; a `SNIPPET:`
bullet without `context:`, a `checked: no|syntax|run` value, an evidence tag other than UNK, or a fenced block right
below it; a `checked: syntax` json, toml or python block that does not parse.
WARN: no H1 title; a Facts bullet mixing tag kinds; header source ids never cited in the body, or cited
ids missing from the header.
"""
import csv, glob, json, os, re, sys

KB = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, os.path.join(KB, "_tools"))
import build_index  # noqa: E402
import kbfacts  # noqa: E402
import kbid  # noqa: E402
SID = kbid.SOURCE_ID  # hash source ids (S-k3f7q2zd) and legacy ones (S123)


SNIPPET = re.compile(r"^- SNIPPET:", re.M)
FENCE = re.compile(r"^```(\w*)[^\n]*\n(.*?)^```", re.M | re.S)


def snippet_problems(body):
    """What is wrong with each `- SNIPPET:` bullet and the fenced block below it."""
    out = []
    for m in SNIPPET.finditer(body):
        rest = body[m.start():]
        bullet = re.split(r"\n(?:\s*\n|(?=```)|(?=- )|(?=#))", rest, maxsplit=1)[0]
        what = " ".join(bullet[2:].split())[:60]
        if not re.search(r"\bcontext:", bullet):
            out.append(f"SNIPPET without `context:`: {what!r}")
        checked = re.search(r"\bchecked:\s*(\w+)", bullet)
        if not checked or checked.group(1) not in ("no", "syntax", "run"):
            out.append(f"SNIPPET without `checked: no|syntax|run`: {what!r}")
        kinds = set(kbfacts.kinds_of(kbfacts.tags_in(bullet)))
        if not kinds - {"UNK"}:
            out.append(f"SNIPPET without an evidence tag (DOC, CODE, DER or COMMUNITY): {what!r}")
        block = FENCE.match(rest[len(bullet):].lstrip("\n"))
        if not block:
            out.append(f"SNIPPET not followed by a fenced code block: {what!r}")
        elif checked and checked.group(1) == "syntax":
            lang, code = block.group(1).lower(), block.group(2)
            try:
                if lang == "json":
                    json.loads(code)
                elif lang == "toml":
                    import tomllib
                    tomllib.loads(code)
                elif lang == "python":
                    compile(code, "<snippet>", "exec")
            except ImportError:
                pass  # tomllib needs Python 3.11
            except Exception as e:  # noqa: BLE001 - any parse error is the finding
                out.append(f"SNIPPET says checked: syntax but its {lang} block does not parse ({type(e).__name__}): {what!r}")
    return out


def candidates(prefixes):
    """Print the CODE and SNIPPET migration candidates (see the module docstring); exit 0."""
    sources = {r["id"]: r for r in csv.DictReader(open("_sources.csv", encoding="utf-8-sig", newline=""))}
    n_code = n_snip = 0
    for u in kbfacts.units(None):
        if prefixes and not any(u["path"].startswith(a.rstrip("/")) for a in prefixes):
            continue
        for part in u["tags"]:
            ids = [i for i in part["ids"] if i in sources]
            if part["kind"] == "DOC" and ids and all(kbfacts.code_file_source(sources[i]) for i in ids):
                n_code += 1
                print(f"CODE-CANDIDATE {u['path']}:{u['line']}  {' '.join(ids)}  {' '.join(u['text'].split())[:90]}")
    for p in sorted(glob.glob("**/*.md", recursive=True)):
        if p.startswith(("_", ".")) or (prefixes and not any(p.startswith(a.rstrip("/")) for a in prefixes)):
            continue
        lines = open(p, encoding="utf-8", errors="replace").read().split("\n")
        inside = False
        for i, ln in enumerate(lines):
            if not ln.startswith("```"):
                continue
            if not inside:
                prev = next((x for x in reversed(lines[:i]) if x.strip()), "")
                bullet = next((x for x in reversed(lines[:i]) if x.startswith("- ")), "")
                if not (prev.startswith(("- SNIPPET:", "  ")) and bullet.startswith("- SNIPPET:")):
                    n_snip += 1
                    print(f"SNIPPET-CANDIDATE {p}:{i + 1}  {ln[3:] or '(no language)'}")
            inside = not inside
    print(f"code_candidates={n_code} snippet_candidates={n_snip}")
    return 0


def main():
    args = [a for a in sys.argv[1:] if a not in ("--json", "--candidates")]
    os.chdir(KB)
    if "--candidates" in sys.argv:
        return candidates(args)
    with open("_coverage.csv", encoding="utf-8-sig", newline="") as f:
        cov = {r["topic"]: r for r in csv.DictReader(f)}
    page = build_index.coverage_page()  # _self/coverage.md (README.md in a kb without it)
    table = open(page, encoding="utf-8").read()
    try:
        gen = {r["topic"]: r for r in build_index.build()[1]}
    except build_index.BuildError as e:
        sys.exit(f"ERROR cannot build the coverage index: {e}")
    rebuild = "(run python3 _tools/build_index.py)"
    sources = {r["id"]: r for r in csv.DictReader(open("_sources.csv", encoding="utf-8-sig", newline=""))}
    out = []

    def add(level, path, msg):
        out.append({"level": level, "path": path, "message": msg})

    for p in sorted(glob.glob("**/*.md", recursive=True)):
        if args and not any(p.startswith(a.rstrip("/")) for a in args):
            continue
        text = open(p, encoding="utf-8", errors="replace").read()
        if not text.startswith("---\n") or "\ntopic:" not in text.split("\n---", 2)[0]:
            continue
        head, body = text.split("\n---", 2)[0], text.split("\n---", 2)[-1]
        fm = dict((k.strip(), v.strip()) for k, _, v in (ln.partition(":") for ln in head.splitlines()[1:]))
        topic, want = fm.get("topic", ""), p[:-3]
        if topic != want:
            add("ERROR", p, f"topic is {topic!r}, path says {want!r}")
        row = gen.get(topic or want)
        if row:  # None: a part of another topic (named in its `files:`), e.g. an artifact digest
            if cov.get(topic) != row:
                add("ERROR", p, f"_coverage.csv row is missing or out of date {rebuild}")
            if build_index.readme_table([row]).splitlines()[-2] not in table.splitlines():
                add("ERROR", p, f"{page} coverage row is missing or out of date {rebuild}")
            for f in filter(None, row["files"].split(";")):
                if not os.path.exists(f):
                    add("ERROR", p, f"_coverage.csv lists missing file {f} (fix `files:` in the front matter)")
        heads = re.findall(r"^## (.+)$", body, re.M)
        for s in ("Summary", "Facts", "Reference", "Examples"):
            if not any(h.startswith(s) for h in heads):
                add("ERROR", p, f"missing section ## {s}")
        if not re.search(r"^# ", body, re.M):
            add("WARN", p, "no '# ' title line")
        for tag in kbfacts.TAG.findall(body):
            for part in kbfacts.parse_tag(tag):
                if not part["ids"] and (part["kind"] in ("DOC", "CODE", "COMMUNITY") or (part["kind"] == "DER" and not part["note"])):
                    add("ERROR", p, f"{part['kind']} tag without a source id: {' '.join(tag.split())[:70]}")
                if part["kind"] == "CODE":
                    if not kbfacts.code_pointer(part):
                        add("ERROR", p, f"CODE tag without a path#symbol pointer: {' '.join(tag.split())[:70]}")
                    for sid in part["ids"]:
                        if sid in sources and not kbfacts.pinned_source(sources[sid]):
                            add("ERROR", p, f"CODE cites {sid}, which is not pinned to a tag or commit (re-source it)")
        for problem in snippet_problems(body):
            add("ERROR", p, problem)
        m = re.search(r"^## Facts.*?$(.*?)(?=^## |\Z)", body, re.M | re.S)
        if m:
            for item in re.split(r"\n(?=- )", m.group(1)):
                item = item.strip()
                if not item.startswith("- "):
                    continue
                kinds = set(kbfacts.kinds_of(kbfacts.tags_in(item)))
                if not kinds:
                    add("ERROR", p, f"untagged fact: {item[2:80]!r}")
                elif len(kinds) > 1:
                    add("WARN", p, f"fact mixes tags {sorted(kinds)}: {item[2:60]!r}")
        cited = {s for tag in re.findall(r"\[(?:DOC|CODE|DER|COMMUNITY)[^\]]*\]", body) for s in SID.findall(tag)}
        fms = set(SID.findall(fm.get("sources", "")))
        if fms - cited:
            add("WARN", p, f"header sources not cited in the body: {' '.join(sorted(fms - cited))}")
        if cited - fms:
            add("WARN", p, f"cited sources missing from the header: {' '.join(sorted(cited - fms))}")

    if "--json" in sys.argv:
        print(json.dumps(out, indent=1))
    else:
        for x in out:
            print(f"{x['level']:<5} {x['path']}: {x['message']}")
        n = sum(1 for x in out if x["level"] == "ERROR")
        print(f"errors={n} warnings={len(out) - n}")
    sys.exit(1 if any(x["level"] == "ERROR" for x in out) else 0)


if __name__ == "__main__":
    sys.exit(main())
